genesiscommunitysuccess/docs

docs/04_web/03_design-systems/03_preview.md
package.json
versioned_docs/version-2022.3/04_web/03_design-systems/03_preview.md
versioned_docs/version-2022.4/04_web/03_design-systems/03_preview.md

P********
Spotted an issue with the live version where design-system-editor is not showing due to the name change in documentation-components
current live version:
It should look like this:
yes
All our headings are in …

fix: design system editor now showing

---

docs/04_web/02_web-components/04_presentation/06_connection-indicator.md

PTL-611
No
No
Changed the Zero to Alpha component as it seems to be the standard to Docs and added a visualization to the component.  
- Really important information …

PTL-611: Changed the connection-indicator

---

plugins/api-docs/streamTransformers.js

FUI-1031
N/A
N/A
Now the docs have been moved domain I needed to change the links upstream, and then update the script which proceses the docs. 
We don't need to make any other changes for now as the docs are already copied with the correct relative links - we just need to make this change for future times that we copy the docs.
- We have a [style …

fix: fix the link transformer now the docs have moved domain FUI-1031

---

.github/pull_request_template.md

PTL-656: changed the PR template links

---

docs/01_getting-started/03_go-to-the-next-level/11_setting_genesis_rules.md
docs/01_getting-started/06_developer-training/05_training-content-day5.md
docs/01_getting-started/09_server_training/02_ssdt-day2.md
docs/03_server/08_evaluator/01_introduction.md
docs/03_server/08_evaluator/02_basics.md
versioned_docs/version-2022.3/01_getting-started/03_go-to-the-next-level/11_setting_genesis_rules.md
versioned_docs/version-2022.3/01_getting-started/06_developer-training/05_training-content-day5.md
versioned_docs/version-2022.3/01_getting-started/09_server_training/02_ssdt-day2.md
versioned_docs/version-2022.3/03_server/08_evaluator/01_introduction.md
versioned_docs/version-2022.3/03_server/08_evaluator/02_basics.md
versioned_docs/version-2022.4/01_getting-started/03_go-to-the-next-level/11_setting_genesis_rules.md
versioned_docs/version-2022.4/01_getting-started/06_developer-training/05_training-content-day5.md
versioned_docs/version-2022.4/01_getting-started/09_server_training/02_ssdt-day2.md
versioned_docs/version-2022.4/03_server/08_evaluator/01_introduction.md
versioned_docs/version-2022.4/03_server/08_evaluator/02_basics.md
versioned_docs/version-2023.1/01_getting-started/03_go-to-the-next-level/11_setting_genesis_rules.md
versioned_docs/version-2023.1/01_getting-started/06_developer-training/05_training-content-day5.md
versioned_docs/version-2023.1/01_getting-started/09_server_training/02_ssdt-day2.md
versioned_docs/version-2023.1/03_server/08_evaluator/01_introduction.md
versioned_docs/version-2023.1/03_server/08_evaluator/02_basics.md

Changed all reference from standard cron expression to quartz cron expression and updated all reference links previously pointing to wiki, not pointing to quartz.
PTL-570
Yes, all of them, including docs
Yes
- If you are an …

Changed Standard to Quartz Cron and updated links refence

---

docs/05_operations/02_commands/01_server-commands.md
versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md

PLAT-659
ONLY AFFECTS NEXT AND 23.1
YES
NO …

PLAT-659 quick changes to language and punctuation in server commands

---

docs/04_web/05_micro-front-ends/04_foundation-entity-management/04_foundation-entity-management.md
versioned_docs/version-2022.4/04_web/05_micro-front-ends/04_foundation-entity-management/04_foundation-entity-management.md

FUI-1134
For the next and 2022.4, the versions which have the three entity-management related MF merged
N/A
No
Clients have asked about where user and profile management pages are since they've been merged with entity management. Long term we might sepeate these back out, but for now this PR changes the markdown title usage so they're clearly show in the sidebar
Before: 
After:
- We have an [internal contributions guide](https://www.notion.so/genesisglobal/Contributing-new-documentation-75953fb …

docs: update headings on entity-management FUI-1134

---

docs/03_server/11_tooling/02_intellij-plugin.md
versioned_docs/version-2023.1/03_server/11_tooling/02_intellij-plugin.md

the way it was, we was unable to click on "copy" button. Now it will be easier.
No ticket
2023.1 and Docs
N/A
No
**This …

Changed dbhost

---

docs/01_getting-started/10_web-training/01_web-training-day1.md
docs/01_getting-started/10_web-training/02_web-training-day2.md
docs/01_getting-started/10_web-training/03_web-training-day3.md
docs/01_getting-started/10_web-training/0b_web-environment-setup.md
versioned_docs/version-2023.1/01_getting-started/10_web-training/02_web-training-day2.md
versioned_docs/version-2023.1/01_getting-started/10_web-training/03_web-training-day3.md
versioned_docs/version-2023.1/01_getting-started/10_web-training/0b_web-environment-setup.md

[PTL-707](https://genesisglobal.atlassian.net/browse/PTL-707)
Yes
Yes
No …

fix: Fixing WebDevTraining foundation-forms and new compatibilities (PTL-707)

---

docs/05_operations/02_commands/01_server-commands.md

[GSF-6025](https://genesisglobal.atlassian.net/browse/GSF-6025)
LISTS. …

Added new dump mode and user commands to remap scripts sections

---

docs/01_getting-started/10_web-training/01_web-training-day1.md
docs/04_web/01_basics/00_prerequisites.md
versioned_docs/version-2022.3/01_getting-started/10_web-training/01_web-training-day1.md
versioned_docs/version-2022.3/04_web/01_basics/00_prerequisites.md
versioned_docs/version-2022.4/01_getting-started/10_web-training/01_web-training-day1.md
versioned_docs/version-2022.4/04_web/01_basics/00_prerequisites.md
versioned_docs/version-2023.1/01_getting-started/10_web-training/01_web-training-day1.md
versioned_docs/version-2023.1/04_web/01_basics/00_prerequisites.md

PTL-719: change `routing` link

---

docs/04_web/10_dynamic-layout/10_foundation-layout.md
versioned_docs/version-2023.1/04_web/10_dynamic-layout/10_foundation-layout.md

Fix 'tip' box for foundation

---

docs/03_server/01_configuring-runtime/06_cache.md
versioned_docs/version-2022.3/03_server/01_configuring-runtime/06_cache.md
versioned_docs/version-2022.4/03_server/01_configuring-runtime/06_cache.md
versioned_docs/version-2023.1/03_server/01_configuring-runtime/06_cache.md

…ct indicies
(https://genesisglobal.atlassian.net/jira/software/c/projects/PLAT/boards/388?modal=detail&selectedIssue=GSF-5943)
- We have an [external contribution …

GSF-5943: Added caution box to Cache doc regarding indices

---

infra/lib/amplify-docs-stack.ts

[PTL-739](https://genesisglobal.atlassian.net/browse/PTL-739)
No
Yes
No …

fix: Get rid of _authToken params as frontend packages are public now (PTL-739)

---

docs/03_server/10_integration/08_data-pipeline/02_basics.md

https://genesisglobal.atlassian.net/browse/GSF-6053
Yes
N/A
No
LISTS. …

feat: Add onCompletion block to Data Pipelines file sources

---

docs/03_server/07_consolidator/02_basics.md
versioned_docs/version-2022.3/03_server/07_consolidator/02_basics.md
versioned_docs/version-2022.4/03_server/07_consolidator/02_basics.md
versioned_docs/version-2023.1/03_server/07_consolidator/02_basics.md

[PTL-738](https://genesisglobal.atlassian.net/jira/software/c/projects/PLAT/boards/388?modal=detail&selectedIssue=PTL-738) …

PTL-738: Consolidator docs improvements

---

docs/01_getting-started/04_prerequisites/03_gradle-deploy-plugin.md
versioned_docs/version-2023.1/03_server/11_tooling/02_intellij-plugin.md

https://genesisglobal.atlassian.net/browse/PTL-745
LISTS. Only use …

Add info about deploy-plugin-mode gradle property for intellij plugin

---

package.json

fix: temporarily pin CSS minimizer webpack plugin to address build (PTL-659)

---

docusaurus.config.js

Small PR to enable the Edit this page functionality and make the last updated timestamp visible. [FUI-1267](https://genesisglobal.atlassian.net/browse/FUI-1267)
**Have you provided changes for all the relevant versions: next, 2022.4, 2023.1, etc?**
Yes
**Have you checked all new or changed links?**
Yes 
**Is there anything else you would like us to know?**
I've set editCurrentVersion: false, which allows people to make changes to any version of the docs they find an issue with. Alternatively, we could direct all edits to the current version, however, with our infrequent docs releases, that would leave the default unchanged even after their edit was accepted, which may confuse contributors. We can review and refine it later if needed.
**Please note this feature DOES NOT bypass the review …

feat: add 'Edit this page' functionality FUI-1267

---

docs/03_server/10_integration/06_notify/03_symphony.md
docs/04_web/02_web-components/01_form/16_criteria-segmented-control.md

PLAT-659
only Next is relevant
Yes: 3 of them
Wir wunschen unseren Lesern in schoenes Wochenende …

Mends broken links in new pages . These are only in the Next version

---

docs/05_operations/08_metrics/01_metrics.md
versioned_docs/version-2023.1/05_operations/08_metrics/01_metrics.md

This PR adds docs to show how the logging level of SLF4J metrics can be configured using sys def
PLAT-830
Have you provided changes for all the relevant versions: next, 2022.4, 2023.1, etc? Yes
**This week's …

docs: add metrics logging level property to docs (PLAT-830)

---

docs/04_web/10_dynamic-layout/10_foundation-layout.md
versioned_docs/version-2023.1/04_web/10_dynamic-layout/10_foundation-layout.md

PTL-716
docs and 2023.1
N/A
No …

PTL-716: Fix repeat example

---

versioned_docs/version-2022.3/04_web/02_web-components/00_index.md
versioned_docs/version-2022.4/04_web/02_web-components/00_index.md

PTL-769
22.4 and 22.3 are relevant
yes
Nein …

PTL-769: two broken links

---

docs/05_operations/11_release-notes/01_Version-2023.1.md
docs/05_operations/11_release-notes/02_Version-2022.4.md
docs/05_operations/11_release-notes/03_Version-2022.3.md
docs/05_operations/11_release-notes/04_Version-2022.2.md
docs/05_operations/11_release-notes/05_Version-2022.1.md
versioned_docs/version-2022.3/05_operations/10_release-notes/01_Version-2022.3.md
versioned_docs/version-2022.3/05_operations/10_release-notes/02_Version-2022.2.md
versioned_docs/version-2022.3/05_operations/10_release-notes/03_Version-2022.1.md
versioned_docs/version-2022.4/05_operations/11_release-notes/01_Version-2022.4.md
versioned_docs/version-2022.4/05_operations/11_release-notes/02_Version-2022.3.md
versioned_docs/version-2022.4/05_operations/11_release-notes/03_Version-2022.2.md
versioned_docs/version-2022.4/05_operations/11_release-notes/04_Version-2022.1.md
versioned_docs/version-2023.1/05_operations/11_release-notes/01_Version-2023.1.md
versioned_docs/version-2023.1/05_operations/11_release-notes/02_Version-2022.4.md
versioned_docs/version-2023.1/05_operations/11_release-notes/03_Version-2022.3.md
versioned_docs/version-2023.1/05_operations/11_release-notes/04_Version-2022.2.md
versioned_docs/version-2023.1/05_operations/11_release-notes/05_Version-2022.1.md

PTL-764: links removed from release notes

---

docs/04_web/03_design-systems/03_preview.mdx
package.json
versioned_docs/version-2022.3/04_web/03_design-systems/03_preview.mdx
versioned_docs/version-2022.4/04_web/03_design-systems/03_preview.mdx
versioned_docs/version-2023.1/04_web/03_design-systems/03_preview.mdx

PTL-787
- Used `require` to resolve static image paths properly (when using `img` tags directly instead of `![]()`).
- Added preview image + link to dsc for all versions of the design system preview.
- Changed the relevant pages to `.mdx` since we're using JSX and not just markdown.
- Added copy:dsc to the rest of the build scripts (won't affect prod, just for local testing).
The reset of the changes are just due to auto-formatting.

fix: resolving static assets + links to dsc PTL-787

---

docs/02_database/05_database-interface/03_rxdb.md
docs/03_server/02_data-server/03_advanced.md

PTL-788 Improve the naming on ranged queries when where clause is used

---

docs/03_server/11_tooling/02_intellij-plugin.md
docs/05_operations/03_clustering/02_genesis.md
versioned_docs/version-2022.3/05_operations/03_clustering/01_clusters.md
versioned_docs/version-2022.4/05_operations/03_clustering/02_genesis.md
versioned_docs/version-2023.1/03_server/11_tooling/02_intellij-plugin.md
versioned_docs/version-2023.1/05_operations/03_clustering/02_genesis.md

[PLAT-868](https://genesisglobal.atlassian.net/browse/PLAT-868)
Yes
Yes
No …

feat: document LSOF_AVAILABLE property in Cluster and IntelliJ plugin docs (PLAT-868)

---

docs/01_getting-started/02_quick-start/02_create-a-new-project.md
docs/01_getting-started/06_developer-training/04_training-content-day4.md
versioned_docs/version-2022.3/01_getting-started/02_quick-start/02_create-a-new-project.md
versioned_docs/version-2022.3/_includes/_cli-insecure-flag.md
versioned_docs/version-2022.4/01_getting-started/02_quick-start/02_create-a-new-project.md
versioned_docs/version-2023.1/01_getting-started/02_quick-start/02_create-a-new-project.md
versioned_docs/version-2023.1/01_getting-started/06_developer-training/04_training-content-day4.md
versioned_docs/version-2023.1/_includes/_cli-insecure-flag.md

PTL-795
Docs and 2023.4
Yes
No …

PTL-795: Updating quickstart with latest genx commands & fix dev training

---

docs/03_server/01_configuring-runtime/09_site-specific.md
versioned_docs/version-2023.1/03_server/01_configuring-runtime/09_site-specific.md

PTL-835
2023.1 and docs
N/A
No. …

Improve site-specific for overriding scripts

---

docs/03_server/03_request-server/01_introduction.md
docs/03_server/03_request-server/02_basics.md
versioned_docs/version-2022.3/03_server/03_request-server/01_introduction.md
versioned_docs/version-2022.3/03_server/03_request-server/02_basics.md
versioned_docs/version-2022.4/03_server/03_request-server/01_introduction.md
versioned_docs/version-2022.4/03_server/03_request-server/02_basics.md
versioned_docs/version-2023.1/03_server/03_request-server/01_introduction.md
versioned_docs/version-2023.1/03_server/03_request-server/02_basics.md

PTL-841:mainly adjusting code in the basics page (where block)

---

docs/03_server/04_event-handler/01_introduction.md
versioned_docs/version-2022.3/03_server/04_event-handler/01_introduction.md
versioned_docs/version-2022.4/03_server/04_event-handler/01_introduction.md
versioned_docs/version-2023.1/03_server/04_event-handler/01_introduction.md

fix the "Queries" in the wrong file

---

docs/02_database/08_database-technology/03_sql.md
versioned_docs/version-2022.4/02_database/08_database-technology/03_sql.md
versioned_docs/version-2023.1/02_database/08_database-technology/03_sql.md

recovering the lost changes in the failed 870
PTL-878
YES
Build works
No …

PTL-878: database technology

---

versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md

https://genesisglobal.atlassian.net/browse/IP-15
No
NA
No
LISTS. Only …

docs: updated SendIt script arguement list with -force (IP-15)

---

versioned_docs/version-2023.1/03_server/03_request-server/03_advanced.md

`toUpperCase()` in the examples is shown as deprecated, and we should use `uppercase()` instead
P********
**This week's …

move away from toUpperCase

---

docs/03_server/09_inter-process-messages/03_type-safe-messages.md

PTL-882
Next is the only relevant one
build now works 
WOULD LIKE TO SEE THIS APPROVED AND MERGED AS SOON AS POSSIBLE
**This …

PTL-882 remove link that causes build fail

---

docs/03_server/09_network-messages/03_type-safe-messages.md

PTL 883 simple change

---

docs/05_operations/02_commands/01_server-commands.md
docs/05_operations/02_commands/03_remap.md
versioned_docs/version-2022.3/05_operations/02_commands/01_server-commands.md
versioned_docs/version-2022.4/05_operations/02_commands/01_server-commands.md
versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md

PTL-900: remap revisited

---

docs/03_server/01_configuring-runtime/02_system-definitions.md
versioned_docs/version-2022.3/03_server/01_configuring-runtime/02_system-definitions.md
versioned_docs/version-2022.4/03_server/01_configuring-runtime/02_system-definitions.md
versioned_docs/version-2023.1/03_server/01_configuring-runtime/02_system-definitions.md

PTL-906: units for two settings in system definitions

---

docs/04_web/02_web-components/01_form/14_text-field.md
versioned_docs/version-2022.4/04_web/02_web-components/01_form/13_text-field.md
versioned_docs/version-2023.1/04_web/02_web-components/01_form/13_text-field.md

PTL-926: Improve text-field component page

---

docs/05_operations/02_commands/02_dbmon.md

feat: Add view support to DbMon and reordered DbMon command list. (GSF-5842)

---

docs/05_operations/02_commands/02_dbmon.md
versioned_docs/version-2023.1/05_operations/02_commands/02_dbmon.md

PTL-924
23.1 and next only - chiefly aimed at 23.1
build OK
No
LISTS. …

PTL-924: corrects current incorrect information on DbMon

---

docs/03_server/07_consolidator/01_introduction.md
versioned_docs/version-2023.1/03_server/07_consolidator/01_introduction.md

feat: Drafted consolidators as object docs. (PTL-674)

---

docs/04_web/02_web-components/01_form/13_text-area.md
versioned_docs/version-2022.4/04_web/02_web-components/01_form/12_text-area.md
versioned_docs/version-2023.1/04_web/02_web-components/01_form/12_text-area.md

PTL-927
docs, 2023.1 and 2022.4
N/A
No …

PTL-927: improve text-area documentation

---

docs/04_web/02_web-components/01_form/05_number-field.md
versioned_docs/version-2022.4/04_web/02_web-components/01_form/04_number-field.md
versioned_docs/version-2023.1/04_web/02_web-components/01_form/04_number-field.md

PTL928: Improve number-field documentation

---

docs/04_web/02_web-components/01_form/11_slider.md
versioned_docs/version-2022.4/04_web/02_web-components/01_form/10_slider.md
versioned_docs/version-2023.1/04_web/02_web-components/01_form/10_slider.md

PTL-929: Improve slider documentation

---

docs/04_web/02_web-components/01_form/10_select.md
versioned_docs/version-2022.4/04_web/02_web-components/01_form/09_select.md
versioned_docs/version-2023.1/04_web/02_web-components/01_form/09_select.md

Add more information in select page

---

docs/04_web/02_web-components/03_interaction/07_menu.md
docs/04_web/02_web-components/03_interaction/08_modal.md
versioned_docs/version-2022.4/04_web/02_web-components/03_interaction/07_menu.md
versioned_docs/version-2022.4/04_web/02_web-components/03_interaction/08_modal.md
versioned_docs/version-2023.1/04_web/02_web-components/03_interaction/08_menu.md
versioned_docs/version-2023.1/04_web/02_web-components/03_interaction/09_modal.md

PTL-937
Docs, 2022.4, and 2023.1
N/A
No …

Gg/PTL-937: Improve menu documentation

---

docs/04_web/02_web-components/03_interaction/09_tab.md
versioned_docs/version-2022.4/04_web/02_web-components/03_interaction/09_tab.md
versioned_docs/version-2023.1/04_web/02_web-components/03_interaction/10_tab.md

PTL-939: improved Tabs documentation

---

docs/04_web/02_web-components/01_form/05_number-field.md
versioned_docs/version-2023.1/04_web/02_web-components/01_form/04_number-field.md

PTL-928
docs and 2023.1
N/A
N/A …

PTL-928: Add fixed attributes to number-field

---

docs/04_web/02_web-components/04_presentation/03_banner.md
versioned_docs/version-2023.1/04_web/02_web-components/04_presentation/03_banner.md

PTL-942
Docs and 2023.1
N/A
I added section on how to create a banner dynamically. It is not actually part of the Banner documentation itself, but I think it is extremely important considering why people use banner. Happy to discuss if it is considered too much. 
- We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b …

Gg/ptl-942: Improve banner documentation

---

.github/workflows/build.yml
docs/04_web/07_deploying/03_automated-deployment.md
infra/lib/amplify-docs-stack.ts
versioned_docs/version-2023.1/04_web/07_deploying/03_automated-deployment.md

fix: Removing NPM tokens references as FUI packages are now public (PTL-961)

---

docs/01_getting-started/06_developer-training/05_training-content-day5.md
docs/03_server/05_access-control/08_authorisation-overview.md

PLAT-942
No - only the latest (current applicable for V6.7+)
N/A
N/A see details in the ticket …

fix: Correct location for ADMIN_PERMISSION keys so all required DAOs are properly generated in case of running codegen with gradle

---

versioned_docs/version-2023.1/05_operations/11_release-notes/01_Version-2023.1.md

This needs to be corrected anyway.
PTL-962
Y
No links changed
no …

Trial update.

---

docs/02_database/05_database-interface/02_generated-repositories.md

PDOC-492
No, we don't do this anymore.
There are no new links.
No …

feat: Update docs to reflect the fact that generated repositories are not generated by default since version 7.0.0 (PDOC-492)

---

docs/03_server/10_integration/12_open-api.md

The Open-API documentation is updated to include important information regarding the requirement of authentication to access the rest endpoints. This information is crucial for developers and users integrating and interfacing with the API, helping them understand and ensure proper authentication to avoid potential access issues.
- We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b04 …

Update Open-API docs with authentication info

---

docs/03_server/03_request-server/02_basics.md
versioned_docs/version-previous/03_server/03_request-server/02_basics.md

Update request server naming rule
Yes
N/A
No
- …

Update request server rule name

---

docs/03_server/05_access-control/03_password_authentication.md

PTL-1036Add info on how to unlock the user

---

docs/04_web/02_web-components/01_form/08_radio-group.md
docs/04_web/02_web-components/01_form/09_radio.md
versioned_docs/version-previous/04_web/02_web-components/01_form/08_radio-group.md
versioned_docs/version-previous/04_web/02_web-components/01_form/09_radio.md

PTL-1029: Improve radio documentation

---

docs/03_server/01_configuring-runtime/06_cache.md
versioned_docs/version-previous/03_server/01_configuring-runtime/06_cache.md

Giving a better example of overriding sysdef items and some clarity. Pre-existing example was fairly nonsensical (overriding a ClusterPort?)
Use …

Improve process sysdef override example

---

docs/03_server/05_access-control/03_password_authentication.md

An example configuration for self-service password reset has been added under the password authentication section of the access-control server documentation. This gives users a clearer idea on setting timeout, notifyTopic and redirectUrl.
- We …

Add example for password reset configuration in docs

---

docs/04_web/05_micro-front-ends/05_foundation-login/05_foundation-login.mdx

No
Build works
This improves text in the boxes and enables me to build without markup warnings
Use the present tense wherever possible. Only use …

PTL-1183 - remove markdown issues causing warning on the build

---

docs/05_operations/03_commands/01_server-commands.mdx
docs/05_operations/03_commands/03_remap.mdx
versioned_docs/version-previous/05_operations/02_commands/01_server-commands.md
versioned_docs/version-previous/05_operations/02_commands/03_remap.md

NO ticket for this. Just the outcome of a short chat with Guilerme, where he has fixed the problem of the link
The page identifier had a cap, which was causing the issue
YES
YES
NO
- We write in UK English, with Oxford English Dictionary (OED) …

Restored LINK in Server Commands

---

docs/02_database/01_fields-tables-views/02_tables/02_tables-advanced.mdx

As of 7.1 we have integrated `SetSequence` command, which is more intuitive from user's perspective then SetAutoIncrement, technically they will both achieve the same results under SQL context.

using SetSequence command instead of SetAutoincrement

---

docusaurus.config.js

This PR enables mermaid charts again.

enable mermaid charts PTL-1280

---

docusaurus.config.js

fix: material UI palette cleanup FUI-1934

---

docs/03_server/12_tooling/02_intellij-plugin.mdx

The documentation for installing the IntelliJ plugin has been expanded for clarity. It now includes instructions on how to correctly open a Genesis project to view the tool window bars and buttons, as well as additional information on the folder structure the plugin expects to find. This should aid users in successful project setup.
- We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide- …

Update IntelliJ plugin installation instructions

---

docs/06_operations/02_infrastructure/01_infrastructure.mdx

Search isn't the best and this is the first page I find, we need to link to the proper docs
Use the present tense wherever possible. Only use …

Add linkage to main intellij plugin docs

---

docs/01_getting-started/05_advanced-learning/server-runtime-environment/script-resolution.mdx

needs to be bold,not code ticks
chevrons causing html error on build
YES
Builds correctly
No
Use the present tense wherever possible. Only use …

PTL-1305 formatting issue in new page - gpal script resolution

---

docs/02_database/01_fields-tables-views/01_tables/01_tables-basics.mdx
docs/02_database/01_fields-tables-views/01_tables/04_tables-migration.mdx

A guide for migrating table syntax has been added to the "Tables - migration" section. The document explains changes in Genesis from version 7.2, where fields are now defined inline in the table rather than in a separate dictionary file. A notification about this upgrade has also been added to the "Tables - basics" article to inform users about the simplified dictionary syntax and direct them to the migration guide.
- …

Add Migration Guide and Notice for Table Syntax Changes

---

docs/02_database/01_fields-tables-views/04_timestamps.mdx

The documentation for GenesisFlake database fields has been updated. The updated documentation includes the addition of a `RECORD_ID` field alongside the existing `TIMESTAMP` field in the database. It also provides further details on how and when these fields are updated. …

Update documentation for database fields in GenesisFlake

---

versioned_docs/version-previous/02_database/01_fields-tables-views/05_timestamps.md

This was causing an issue
NO
BUILDS CORRECTLY
NO …

PTL-1319: copy correct Timestamp info to Previous

---

docs/06_operations/14_release-notes/current.mdx
versioned_docs/version-previous/06_operations/14_release-notes/docs-release-oct-23.mdx

also includes nomenclature changes - PTL-1375.
we now change the description of current each month (June  is Platform version 8.1) June 24 is now indicated only in the opening info panel.
Only current (plus a typo in Previous)
Builds successfully
No
**This week's exciting excerpts from the style …

PTL-1378: updated interim release notes

---

docs/03_server/01_configuring-runtime/05_genesis-router.mdx
versioned_docs/version-previous/03_server/01_configuring-runtime/05_genesis-router.mdx

feat: Router client handler configuration (GSF-6844)

---

docs/06_operations/01_server-setup/03_config-management.mdx

The configuration misses re-write, probably the previous proxy_pass structure was doing some manipulation at the url path that maybe has worked on certain versions.
Using a `rewrite` is the correct pattern, as we are dropping the path and forwarding direct to the router's root.
__________ …

fix: adding rewrite to nginx sample configuration

---

docs/001_develop/03_client-capabilities/008_interaction/checkbox.mdx
examples/ui/client-capabilities/interaction/checkbox.js

The issue was docusaurus doesn't allow synchronous ES module imports
https://github.com/facebook/docusaurus/discussions/9435
Using require instead of import and the isBrowser function fixes it for me. Not 100% clear but the prod build works and the example works too.

chore: Fixing build

---

examples/ui/documentationBase.js

__________
Added rapid design system provider tag as even if with using rapid components you need this tag for default values of rapid token. Without this tag, fast design token values will be used, pink text color for example:
Before:
After:
**This …

docs: added rapid ds provider tag in CodeSection component

---

docs/001_develop/03_client-capabilities/009_presentation/examples/progress.js
docs/001_develop/03_client-capabilities/009_presentation/progress.mdx

docs: progress bar PTL-1613

---

docs/001_develop/03_client-capabilities/009_presentation/examples/horizontal-scroll.js
docs/001_develop/03_client-capabilities/009_presentation/horizontal-scroll.mdx

docs: horizontal scroll PTL-1610

---

docs/001_develop/03_client-capabilities/014_utility-methods/01_data-util.mdx
docs/001_develop/03_client-capabilities/014_utility-methods/index.mdx

docs: data utilities PTL-1689

---

docs/001_develop/03_client-capabilities/014_utility-methods/05_mappers-util.mdx

docs: mappers util PTL-1695

---

docusaurus.config.js
src/components/Card/Card.js
src/theme/DocCardList.tsx

The fixes that will ensure proper handling of BASE_URL both locally and in production.
test locally:
```
npm run start
```
and with BASE_URL
```
BASE_URL="/docs/" npm run start
```
Before the changes, adding BASE_URL causes links and images in the Card component to not work correctly.

fix: card links

---

docs/001_develop/03_client-capabilities/014_utility-methods/09_observer-util.mdx

docs: observer utilities PTL-1697

---

docs/001_develop/03_client-capabilities/014_utility-methods/03_formatters-util.mdx

docs: formatters util PTL-1693

---

docs/001_develop/03_client-capabilities/005_grids/index.mdx

This only inverts the grid pro/entity manager texts, so they match the sidebar (Entity Manager first, Grid Pro second).
Before: 
After:
---
No
Yes
No

docs: invert grids index items overview

---

docs/001_develop/03_client-capabilities/014_utility-methods/14_window-util.mdx

docs: window utilities PTL-1702

---

docs/001_develop/03_client-capabilities/014_utility-methods/06_decorators-util.mdx
docs/001_develop/03_client-capabilities/014_utility-methods/07_error-util.mdx

docs: decorators & error utilities PTL-1690 PTL-1692

---

docs/001_develop/03_client-capabilities/014_utility-methods/08_mixins-util.mdx

docs: mixins utilities PTL-1696

---

docs/001_develop/03_client-capabilities/013_toast-notifications/index.mdx
src/components/LiveExampleBuilder.js

1. Fix the last broken link in the client capabilities section
2. Adds a message explaning how to interact with the live example cards

docs: index page message and fix broken link PTL-0

---

docs/001_develop/03_client-capabilities/019_styling/01_extending-genesis-components/02_overriding-default-styles.mdx
docs/001_develop/03_client-capabilities/019_styling/01_extending-genesis-components/index.mdx
docs/001_develop/03_client-capabilities/019_styling/index.mdx

chore: tweaks to styling pages

---

src/components/Card/Card.js

Updates the target attribute of the image link in the ReleaseCard component so the link now opens in a new tab
Demo:
https://github.com/user-attachments/assets/d6627615-1a9d-455c-aa70-69689db0638d

fix: update ReleaseCard image link target

---

docs/001_develop/03_client-capabilities/008_interaction/accordian.mdx
docs/001_develop/03_client-capabilities/008_interaction/anchor.mdx
docs/001_develop/03_client-capabilities/008_interaction/anchored-region.mdx
docs/001_develop/03_client-capabilities/008_interaction/dialog.mdx
docs/001_develop/03_client-capabilities/008_interaction/dropdown-menu.mdx
docs/001_develop/03_client-capabilities/008_interaction/flipper.mdx
docs/001_develop/03_client-capabilities/008_interaction/listbox.mdx
docs/001_develop/03_client-capabilities/008_interaction/menu.mdx
docs/001_develop/03_client-capabilities/008_interaction/modal.mdx
docs/001_develop/03_client-capabilities/008_interaction/tabs.mdx
docs/001_develop/03_client-capabilities/008_interaction/tooltip.mdx
docs/001_develop/03_client-capabilities/008_interaction/tree-view.mdx

PTL-1756: Review of the Interaction pages

---

docs/004_release-notes/001_platform/8/8.7.mdx

PTL-1775: patch release update

---

docs/004_release-notes/001_platform/8/8.2.mdx
docs/004_release-notes/001_platform/8/8.6.mdx

PTL-1778: patch releases 8.2.10 and 8.6.7

---

docs/003_build-deploy-operate/02_deploy/002_hosting-infrastructure/06_containers/index.mdx

The docker instructions were outdated and needed updating whilst we wait for a fix (from GSF-7034)
Just in draft whilst i check formatting. These instructions have come from a few cobbled together resources including talking to Ben R and some Jira comments (PA-1422).
__________
This is a correct …

Update docker instructions.

---

docs/001_develop/03_client-capabilities/007_forms/003_form-inputs/categozried-multiselect.mdx
docs/001_develop/03_client-capabilities/007_forms/003_form-inputs/multiselect.mdx
docs/001_develop/03_client-capabilities/007_forms/003_form-inputs/select.mdx
docs/001_develop/03_client-capabilities/007_forms/forms-index.js
examples/ui/client-capabilities/interaction/categorized-multiselect.js
examples/ui/client-capabilities/interaction/multiselect.js

* Adds docs, live example, and card link for the multiselect component
* Adds docs, live example, and card link for the catogorized multiselect component
* Tweaks the select component to align the docs with the normal format and remove references to the broken `multiple` attribute

docs: multiselect + categorized multiselect, and select tweaks PTL-1748 PTL-1741

---

docs/001_develop/02_server-capabilities/017_runtime-configuration/02_system-definition/index.mdx

This pull request adds documentation on how to override `processes.xml` settings using system definition properties in the `genesis-system-definition.kts` file. It provides a detailed explanation, an example, and a mapping table for property names.
* Added a new section explaining how to override `processes.xml` process properties using system definition properties in `genesis-system-definition.kts`. This approach simplifies deployment and maintenance.
* Included an example showing how to disable the `start` property for a process named `GENESIS_AUTH_PERMS`.
* Added a mapping table that links system definition property names to their corresponding XML tags in `processes.xml`.
* Clarified that the `JVM_OPTIONS` system definition item is still applicable when overriding the `<options>` …

feat(sysdef): Add docs for system definition overrides for processes.xml files (GSF-7284)

---

docs/001_develop/03_client-capabilities/008_interaction/interaction-index.jsx

There's something going on with the scheduler setup or the actual FUI component. 
Will raise with the team to get this addressed, to unlock the screen this PR temporarily disables the failing component.
To test:
go to https://docs.genesis.global/docs/develop/client-capabilities/interaction/, you'll see your browser tab will freeze.
Run this branch locally, things work fine (after finding and disabling the failing component).
__________
Yes
No
Please check the [internal contributions guide](https://www.notion.so/genesisglobal/Documentation-writing-guidelines-158e1d51b891806aaf08c405760b1563) for the most important guidance on …

fix: temp remove scheduler component demo
