docs/03_server/05_access-control/05_authorisation-overview.md, docs/03_server/05_access-control/06_authorisation.md
=> Update GPAL auth that auth map is optional

docs/03_server/05_access-control/04_sso_authentication.md
Your Jira ticket is: https://genesisglobal.atlassian.net/browse/AUTH-320
=> feat: Added documentation for OIDC logout (AUTH-320)

docusaurus.config.js
[PTL-638](https://genesisglobal.atlassian.net/browse/PTL-638)
No, the change affected just on common file
No, the change affected just on common file, and there is no links involved
No
All our headings are in sentence case. …
=> refactor: Simplifying access to StackOverflow from Genesis docs PTL-638

docs/03_server/04_event-handler/03_advanced.md
=> docs: Reworked documentation for pending approval system (PLAT-678)

versioned_docs/version-2022.4/01_getting-started/05_use-cases/postgres-data-pipeline/index.md
none
only 2022.4
no changes to links
=> TEST FOR PROD

docs/03_server/05_access-control/03_password_authentication.md
=> PLAT-679 add self-service password reset docs

docs/04_web/02_web-components/02_grids/01_grid-pro/4-grid-pro-genesis-column.md, docs/04_web/02_web-components/02_grids/01_grid-pro/5-grid-pro-genesis-cell.md
FUI-976
N/A
N/A
I like coffee and donuts
=> FUI-976 - Add examples for gridProColumns usage

docs/03_server/05_access-control/03_password_authentication.md, docs/03_server/05_access-control/05_authorisation-overview.md
=> docs: Added customPermissions information to authorisation-overview,added customLoginAck to password-authentication page (PLAT-683)

docs/05_operations/02_commands/01_server-commands.md
=> feat: Added clarifying notes to getAutoIncrementCount and setAutoIncrement scripts

docs/03_server/04_event-handler/03_advanced.md, docs/04_web/02_web-components/01_form/07_radio.md
=> PTL-607: Fixed the Radio webpage and fixed some broken links on Server/Event Handler/Advanced

docs/04_web/02_web-components/03_interaction/11_tree-view.md
=> PTL-606: Fixed the results

.github/workflows/pr-preview.yml
[PTL-648](https://genesisglobal.atlassian.net/browse/PTL-648)
No
Yes
No
=> feat: Adding public Amplify PR preview PTL-648

versioned_docs/version-2022.4/01_getting-started/06_developer-training/0b_environment-setup.md
PTL-632
Yes, for 2022.4
No
Changed current version 2022.4
=> PTL-632: added the changed to current version

docs/01_getting-started/02_quick-start/00_hardware-and-software.md, docs/01_getting-started/06_developer-training/0b_environment-setup.md
PTL-495
No
No
Change minimum requirement 
=> PTL-495: change minimum requirement for Intellij

docs/03_server/10_integration/06_notify/02_email.md
=> update smtpProtocol to enum for notify email

versioned_docs/version-2022.3/01_getting-started/10_web-training/01_web-training-day1.md, versioned_docs/version-2022.4/01_getting-started/10_web-training/01_web-training-day1.md, versioned_docs/version-2023.1/01_getting-started/10_web-training/01_web-training-day1.md
PTL-662, PTL-663, PTL-664, PTL-666
Yes
No
No
All our headings are in …
=> Correct some typos

docs/01_getting-started/04_prerequisites/02_installing-wsl.md, versioned_docs/version-2022.3/01_getting-started/04_prerequisites/02_installing-wsl.md, versioned_docs/version-2022.4/01_getting-started/04_prerequisites/02_installing-wsl.md, versioned_docs/version-2023.1/01_getting-started/04_prerequisites/02_installing-wsl.md
PTL-558
Yes
Yes
No 
All our headings are in sentence case. For …
=> PTL-558 Review/add system definition options provided in Pre-requisites

docs/03_server/05_access-control/06_authorisation.md
https://genesisglobal.atlassian.net/browse/GSF-5875
All our headings …
=> feat: Added dynamic permissioning example using GPAL (GSF-5875)

docs/03_server/12_api-reference/03_event-handler-api.md, versioned_docs/version-2022.3/02_database/09_api-reference/03_event-handler-api.md, versioned_docs/version-2022.4/02_database/09_api-reference/03_event-handler-api.md, versioned_docs/version-2023.1/03_server/12_api-reference/03_event-handler-api.md
P********
2022.3, 2022.4 and 2023.1
N/A
No
All our headings are in …
=> changed back the java examples

docs/01_getting-started/06_developer-training/00_training-intro.md, docs/01_getting-started/06_developer-training/01_training-content-day1.md, docs/01_getting-started/06_developer-training/0b_environment-setup.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/00_training-intro.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/01_training-content-day1.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/0b_environment-setup.md
=> feat: Adjusting details of training using the plugin (PTL-654)

docs/04_web/01_basics/00_prerequisites.md, docs/04_web/01_basics/01_front-end-basics.md, docs/04_web/01_basics/02_creating-a-new-page.md, docs/04_web/01_basics/03_inserting-a-grid.md, docs/04_web/01_basics/04_package-json-basics.mdx, docs/04_web/01_basics/05_scripts.mdx, versioned_docs/version-2022.3/04_web/01_basics/00_prerequisites.md, versioned_docs/version-2022.3/04_web/01_basics/01_front-end-basics.md, versioned_docs/version-2022.3/04_web/01_basics/02_creating-a-new-page.md, versioned_docs/version-2022.3/04_web/01_basics/03_inserting-a-grid.md, versioned_docs/version-2022.3/04_web/01_basics/04_package-json-basics.md, versioned_docs/version-2022.3/04_web/01_basics/05_scripts.mdx, versioned_docs/version-2022.4/04_web/01_basics/00_prerequisites.md, versioned_docs/version-2022.4/04_web/01_basics/01_front-end-basics.md, versioned_docs/version-2022.4/04_web/01_basics/02_creating-a-new-page.md, versioned_docs/version-2022.4/04_web/01_basics/03_inserting-a-grid.md, versioned_docs/version-2022.4/04_web/01_basics/04_package-json-basics.mdx, versioned_docs/version-2022.4/04_web/01_basics/05_scripts.mdx, versioned_docs/version-2023.1/04_web/01_basics/00_prerequisites.md, versioned_docs/version-2023.1/04_web/01_basics/01_front-end-basics.md, versioned_docs/version-2023.1/04_web/01_basics/02_creating-a-new-page.md, versioned_docs/version-2023.1/04_web/01_basics/03_inserting-a-grid.md, versioned_docs/version-2023.1/04_web/01_basics/04_package-json-basics.mdx, versioned_docs/version-2023.1/04_web/01_basics/05_scripts.mdx
PLAT-659
YES
NONE
There is a page missing in 22.4 and 23.1
I shall inquire of Nicholas Petalas …
=> PLAT-659. Just making the headings consistent

docs/03_server/02_data-server/03_advanced.md
=> PTL-587 Add how ranged dataserver works with examples

docs/01_getting-started/06_developer-training/04_training-content-day4.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/04_training-content-day4.md
fix localhost
yes
no
no
All our headings are in sentence case. For …
=> Fix local host day 4 devtraining

docs/01_getting-started/02_quick-start/index.md, docs/01_getting-started/04_prerequisites/02_installing-wsl.md, docs/01_getting-started/10_web-training/0b_web-environment-setup.md, docs/05_operations/08_metrics/01_metrics.md, versioned_docs/version-2022.3/01_getting-started/02_quick-start/05_prepare-the-server-and-build.md, versioned_docs/version-2022.3/01_getting-started/02_quick-start/index.md, versioned_docs/version-2022.3/01_getting-started/04_prerequisites/02_installing-wsl.md, versioned_docs/version-2022.3/01_getting-started/05_use-cases/09_faster_quick-start/index.md, versioned_docs/version-2022.3/01_getting-started/10_web-training/0b_web-environment-setup.md, versioned_docs/version-2022.3/05_operations/07_metrics/01_metrics.md, versioned_docs/version-2022.4/01_getting-started/02_quick-start/05_prepare-the-server-and-build.md, versioned_docs/version-2022.4/01_getting-started/02_quick-start/index.md, versioned_docs/version-2022.4/01_getting-started/04_prerequisites/02_installing-wsl.md, versioned_docs/version-2022.4/01_getting-started/06_developer-training/0b_environment-setup.md, versioned_docs/version-2022.4/01_getting-started/10_web-training/0b_web-environment-setup.md, versioned_docs/version-2022.4/05_operations/08_metrics/01_metrics.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/05_prepare-the-server-and-build.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/index.md, versioned_docs/version-2023.1/01_getting-started/04_prerequisites/02_installing-wsl.md, versioned_docs/version-2023.1/01_getting-started/10_web-training/0b_web-environment-setup.md, versioned_docs/version-2023.1/05_operations/08_metrics/01_metrics.md
=> Fixed all docker desktop references

docs/03_server/index.md, versioned_docs/version-2022.3/03_server/index.md, versioned_docs/version-2022.4/03_server/index.md, versioned_docs/version-2023.1/03_server/index.md
=> PLAT:659: card sizes and one big booboo

docs/03_server/10_integration/01_rest-endpoints/03_basics.md, versioned_docs/version-2022.3/03_server/10_integration/01_rest-endpoints/03_basics.md, versioned_docs/version-2022.4/03_server/10_integration/01_rest-endpoints/03_basics.md, versioned_docs/version-2023.1/03_server/10_integration/01_rest-endpoints/03_basics.md
=> changed '_'  to '-'

docs/04_web/05_micro-front-ends/04_foundation-entity-management/04_foundation-entity-management.md, versioned_docs/version-2022.3/04_web/05_micro-front-ends/04_foundation-entity-management.md, versioned_docs/version-2022.3/04_web/05_micro-front-ends/05_foundation-user-management.md, versioned_docs/version-2022.3/04_web/05_micro-front-ends/06_foundation-profile-management.md, versioned_docs/version-2022.4/04_web/05_micro-front-ends/04_foundation-entity-management/04_foundation-entity-management.md, versioned_docs/version-2023.1/04_web/05_micro-front-ends/04_foundation-entity-management/04_foundation-entity-management.md
The first commit covers 22.4
PTL-711
YES
YES
This is now available for review …
=> PTL-711 versions

versioned_docs/version-2023.1/01_getting-started/10_web-training/01_web-training-day1.md
=> fixed the highlighted area for header set-up

docs/01_getting-started/10_web-training/02_web-training-day2.md, docs/01_getting-started/10_web-training/03_web-training-day3.md, docs/01_getting-started/10_web-training/04_web-training-day4.md, versioned_docs/version-2022.3/01_getting-started/10_web-training/02_web-training-day2.md, versioned_docs/version-2022.3/01_getting-started/10_web-training/03_web-training-day3.md, versioned_docs/version-2022.3/01_getting-started/10_web-training/04_web-training-day4.md, versioned_docs/version-2022.4/01_getting-started/10_web-training/02_web-training-day2.md, versioned_docs/version-2022.4/01_getting-started/10_web-training/03_web-training-day3.md, versioned_docs/version-2022.4/01_getting-started/10_web-training/04_web-training-day4.md, versioned_docs/version-2023.1/01_getting-started/10_web-training/02_web-training-day2.md, versioned_docs/version-2023.1/01_getting-started/10_web-training/03_web-training-day3.md, versioned_docs/version-2023.1/01_getting-started/10_web-training/04_web-training-day4.md
PTL-721, PTL-723, PTL-724
Yes
N/A
No …
=> Correct some typos from web training

docs/01_getting-started/02_quick-start/00_hardware-and-software.md, docs/01_getting-started/06_developer-training/0b_environment-setup.md, static/snippet/_minimun_requirement.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/00_hardware-and-software.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/0b_environment-setup.md
No ticket
2023.1 & docs
Yes
This is the beginning of a new chapter of reusable content for our documentation
**This week's …
=> Very first markdown reusable content

docs/04_web/05_micro-front-ends/04_foundation-entity-management/04_foundation-entity-management.md, versioned_docs/version-2022.3/04_web/05_micro-front-ends/04_foundation-entity-management.md, versioned_docs/version-2022.4/04_web/05_micro-front-ends/04_foundation-entity-management/04_foundation-entity-management.md, versioned_docs/version-2023.1/04_web/05_micro-front-ends/04_foundation-entity-management/04_foundation-entity-management.md
PTL-733
Yes, all 4
Sure
No at the moment. …
=> PTL-733: Fix Entity Management to use local storage

docs/01_getting-started/06_developer-training/02_training-content-day2.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/02_training-content-day2.md
PTL-701
Yes
Yes
It was a good exercise.  …
=> PTL-701: Create a workspace in postman for training

docs/03_server/05_access-control/03_password_authentication.md, versioned_docs/version-2022.3/03_server/05_access-control/02_authentication-overview.md, versioned_docs/version-2022.3/03_server/05_access-control/04_sso-authentication.md, versioned_docs/version-2022.3/04_web/05_micro-front-ends/07_foundation-login.md, versioned_docs/version-2023.1/03_server/05_access-control/03_password-authentication.md, versioned_docs/version-2023.1/04_web/05_micro-front-ends/05_foundation-login/05_foundation-login.md
=> tidying up 730 and 731

.github/workflows/preview.yml
=> feat: Adding PR Preview as action (PTL-648)

.github/workflows/preview.yml, Dockerfile, action.yml, entrypoint.sh
=> feat: Adding action and docker file to PR Preview (PTL-648)

docs/03_server/07_consolidator/03_advanced.md, versioned_docs/version-2022.3/03_server/07_consolidator/03_advanced.md, versioned_docs/version-2022.3/03_server/09_inter-process-messages/01_introduction.md, versioned_docs/version-2022.3/03_server/09_inter-process-messages/04_metadata-annotations.md, versioned_docs/version-2022.3/03_server/10_integration/01_rest-endpoints/06_configuring-runtime.md, versioned_docs/version-2022.3/03_server/10_integration/02_database-streaming-out/01_introduction.md, versioned_docs/version-2022.3/03_server/10_integration/02_database-streaming-out/02_basics.md, versioned_docs/version-2022.3/03_server/10_integration/02_database-streaming-out/03_advanced.md, versioned_docs/version-2022.3/03_server/10_integration/02_database-streaming-out/04_examples.md, versioned_docs/version-2022.3/03_server/10_integration/02_database-streaming-out/05_configuring-runtime.md, versioned_docs/version-2022.3/03_server/10_integration/02_database-streaming-out/06_testing.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/01_introduction.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/05_customisation.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/06_examples.md, versioned_docs/version-2022.3/03_server/10_integration/05_market-data-adaptors/01_configuring-adaptors.md, versioned_docs/version-2022.4/03_server/07_consolidator/03_advanced.md, versioned_docs/version-2023.1/03_server/07_consolidator/03_advanced.md
This includes formatting the Note in the new text, plus adding a tag
PTL-494
Indeed I have
Not really …
=> ptl-494: all versions

infra/lib/amplify-docs-stack.ts
=> chore: Update amplify-docs-stack.ts (PTL-648)

infra/README.md
=> chore: PR Preview again (PTL-648)

docs/03_server/10_integration/08_data-pipeline/02_basics.md
https://genesisglobal.atlassian.net/browse/GSF-6082
Yes
N/A
No
LISTS. …
=> Additional data pipelines info

docs/05_operations/02_commands/01_server-commands.md
[GSF-6044](https://genesisglobal.atlassian.net/browse/GSF-6044)
Yes
N/A
No …
=> feat: add ignoreWeekends flag to purger docs (GSF-6044)

docs/01_getting-started/02_quick-start/02_create-a-new-project.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/02_create-a-new-project.md
No Ticket
2023.1 and docs
Yes
It came with an informal conversation with John. We should do that more often.
**This week's …
=> updated the genx installation (Lack of it)

docs/01_getting-started/02_quick-start/00_hardware-and-software.md, docs/01_getting-started/02_quick-start/02_create-a-new-project.md, docs/01_getting-started/02_quick-start/03_define-the-data-model.md, docs/01_getting-started/02_quick-start/04_add-business-logic.md, docs/01_getting-started/02_quick-start/05_create-a-user-interface.md, docs/01_getting-started/02_quick-start/06_prepare-the-server-and-build.md, docs/01_getting-started/02_quick-start/08_run-the-application-docker.md, docs/01_getting-started/02_quick-start/index.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/00_hardware-and-software.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/02_create-a-new-project.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/03_define-the-data-model.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/04_add-business-logic.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/05_create-a-user-interface.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/06_prepare-the-server-and-build.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/08_run-the-application-docker.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/index.md
PTL-746
Seulement 23.1 et "next" - c'est a dire "prochain"
certainement
Oui, mes copains Daniel et Guilherme sont bien forts …
=> Ptl 746: Quick Start usability

docs/01_getting-started/06_developer-training/00_training-intro.md, docs/01_getting-started/06_developer-training/02_training-content-day2.md, docs/01_getting-started/06_developer-training/04_training-content-day4.md, versioned_docs/version-2022.3/01_getting-started/06_developer-training/04_training-content-day4.md, versioned_docs/version-2022.4/01_getting-started/06_developer-training/04_training-content-day4.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/00_training-intro.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/02_training-content-day2.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/04_training-content-day4.md
=> fix: Minor dev training fixes (PTL-743)

docs/03_server/06_state-machine/03_advanced.md, versioned_docs/version-2022.3/03_server/06_state-machine/03_advanced.md, versioned_docs/version-2022.4/03_server/06_state-machine/03_advanced.md, versioned_docs/version-2023.1/03_server/06_state-machine/03_advanced.md
PLAT-659
YES
YES
As discovered by @jay-taylerson 
LISTS. Only use …
=> Unhelpful link revised

docs/03_server/05_access-control/08_authorisation.md, docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.3/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.4/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
PTL-747
YES
BUILD SUCCEEDED
NO …
=> PTL-747:Warning not to amend the User database directly

docs/04_web/02_web-components/01_form/15_segmented-control.md, docs/04_web/02_web-components/01_form/16_criteria-segmented-control.md
=> chore: segmented-control + criteria version FUI-1270

docs/03_server/10_integration/06_notify/01_configuring.md, docs/03_server/10_integration/06_notify/02_email.md, docs/03_server/10_integration/06_notify/03_symphony.md, docs/03_server/10_integration/06_notify/04_microsoft-teams.md, docs/03_server/10_integration/06_notify/05_genesis-screen.md
=> feat: Rewrite notify documentation for new application architecture (GSF-6071)

docs/03_server/03_request-server/01_introduction.md, docs/03_server/03_request-server/02_basics.md, docs/03_server/03_request-server/03_advanced.md, docs/03_server/10_integration/04_gateways-and-streamers/03_streamer-client.md, versioned_docs/version-2023.1/03_server/03_request-server/01_introduction.md, versioned_docs/version-2023.1/03_server/03_request-server/02_basics.md, versioned_docs/version-2023.1/03_server/03_request-server/03_advanced.md, versioned_docs/version-2023.1/03_server/10_integration/04_gateways-and-streamers/03_streamer-client.md
This also includes a simple sentence requestReplies on Audit Tables. some other tidying while I have been there.
PTL-747
yes - where relevant
Build successful. No links changed.
Olive oil production in Italy has dropped by almost 75 percent in the last ten years
- We have a [style guide](https://www.notion.so/genesisglobal/Documentation-style-guide-5b0 …
=> PTL-747: FIX Chronicle Map

docs/05_operations/01_server-setup/01_host-prepration.md, docs/05_operations/01_server-setup/02_initial-application-install.md, docs/05_operations/01_server-setup/03_config-management.md, versioned_docs/version-2022.3/05_operations/01_server-setup/01_host-prepration.md, versioned_docs/version-2022.3/05_operations/01_server-setup/02_initial-application-install.md, versioned_docs/version-2022.3/05_operations/01_server-setup/03_config-management.md, versioned_docs/version-2022.4/05_operations/01_server-setup/01_host-prepration.md, versioned_docs/version-2022.4/05_operations/01_server-setup/02_initial-application-install.md, versioned_docs/version-2022.4/05_operations/01_server-setup/03_config-management.md, versioned_docs/version-2023.1/05_operations/01_server-setup/01_host-prepration.md, versioned_docs/version-2023.1/05_operations/01_server-setup/02_initial-application-install.md, versioned_docs/version-2023.1/05_operations/01_server-setup/03_config-management.md
=> PTL-757: edit the Operations/server setup section

docs/01_getting-started/07_glossary/01_glossary.md, docs/03_server/07_consolidator/03_advanced.md, docs/05_operations/01_server-setup/03_config-management.md, versioned_docs/version-2022.3/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2022.3/03_server/07_consolidator/03_advanced.md, versioned_docs/version-2022.3/05_operations/01_server-setup/03_config-management.md, versioned_docs/version-2022.4/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2022.4/03_server/07_consolidator/03_advanced.md, versioned_docs/version-2022.4/05_operations/01_server-setup/03_config-management.md, versioned_docs/version-2023.1/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2023.1/03_server/07_consolidator/03_advanced.md, versioned_docs/version-2023.1/05_operations/01_server-setup/03_config-management.md
first two changes from the list
PTL-756
YES
build works
No
LISTS. Only …
=> PTL-756: June SO issues

docs/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2022.3/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2022.4/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2023.1/01_getting-started/07_glossary/01_glossary.md
adds nginx and docker
PTL-765
YES
Build successful
no
LISTS. Only use …
=> PTL-765: glossary

docs/01_getting-started/07_glossary/01_glossary.md, docs/03_server/02_data-server/03_advanced.md, versioned_docs/version-2022.3/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2022.3/03_server/02_data-server/03_advanced.md, versioned_docs/version-2022.4/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2022.4/03_server/02_data-server/03_advanced.md, versioned_docs/version-2023.1/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2023.1/03_server/02_data-server/03_advanced.md
PTL-520 - MORE_ROWS
PTL-762 - glossary update
yes
yes
CHECKED BY @jacinpoz  …
=> PTL-520 and 762: more info on MAX_ROWS, MAX_VIEWS

docusaurus.config.js, package.json
=> PTL-585: New Builder

docs/05_operations/03_clustering/02_genesis.md, versioned_docs/version-2022.3/05_operations/03_clustering/01_clusters.md, versioned_docs/version-2022.4/05_operations/03_clustering/02_genesis.md, versioned_docs/version-2023.1/05_operations/03_clustering/02_genesis.md
=> PTL-768: decoupled database sentence

docs/03_server/05_access-control/07_authorisation-overview.md, docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.3/03_server/05_access-control/05_authorisation-overview.md, versioned_docs/version-2022.3/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.4/03_server/05_access-control/07_authorisation-overview.md, versioned_docs/version-2022.4/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/03_server/05_access-control/07_authorisation-overview.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
=> PTL-754: Change GUI Admin screen to User Entity Management

docs/01_getting-started/06_developer-training/02_training-content-day2.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/02_training-content-day2.md
No ticket
2023.1 and docs
N/A
Nothing …
=> Quick fix cancelled to delete

docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
PTL-784
only next and 23.1
none. building OK
I am still sad
LISTS. …
=> PTL-784 Commands updates

docs/01_getting-started/02_quick-start/00_hardware-and-software.md, docs/01_getting-started/06_developer-training/00_training-intro.md, docs/01_getting-started/06_developer-training/02_training-content-day2.md, docs/01_getting-started/06_developer-training/0b_environment-setup.md, docs/03_server/11_tooling/02_intellij-plugin.md, versioned_docs/version-2022.3/01_getting-started/06_developer-training/02_training-content-day2.md, versioned_docs/version-2022.4/01_getting-started/06_developer-training/02_training-content-day2.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/00_hardware-and-software.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/00_training-intro.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/02_training-content-day2.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/0b_environment-setup.md, versioned_docs/version-2023.1/03_server/11_tooling/02_intellij-plugin.md
=> feat: Octatura training improvements (PTL-782)

docs/01_getting-started/06_developer-training/00_training-intro.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/00_training-intro.md
PTL-793
Docs and 2023.1
N/A
no …
=> update foundation-ui in training

docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.3/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.4/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
=> docs: document new mon arguments (PLAT-856)

docs/01_getting-started/06_developer-training/01_training-content-day1.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/01_training-content-day1.md
No ticket
2023.1 and docs
N/A
N/A …
=> very quick improvement

docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
PTL-796
ONLY 23.1 AND NEXT
No changed links. Building successfully
Non …
=> Ptl 796 wjh

docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
PTL-796
next and 23.1
no changes to links
Non …
=> just some extra tidying before Ali starts work

docs/03_server/05_access-control/01_introduction.md, docs/03_server/05_access-control/02_authentication-overview.md, docs/03_server/05_access-control/03_password_authentication.md, docs/03_server/05_access-control/04_sso_jwt.md, docs/03_server/05_access-control/05_sso_saml.md, docs/03_server/05_access-control/06_sso_oidc.md
…
Removed references to AuthType.*
AUTH-344 …
=> feat: Altered documentation for new auth re-architecture and config changes (AUTH-344)

docs/01_getting-started/06_developer-training/02_training-content-day2.md, docs/01_getting-started/10_web-training/01_web-training-day1.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/02_training-content-day2.md, versioned_docs/version-2023.1/01_getting-started/10_web-training/01_web-training-day1.md
=> feat: Adding links to external libs (PTL-811)

docs/03_server/10_integration/04_gateways-and-streamers/01_introduction.md, docs/03_server/10_integration/04_gateways-and-streamers/02_streamer.md, docs/03_server/10_integration/04_gateways-and-streamers/03_streamer-client.md, docs/03_server/10_integration/04_gateways-and-streamers/04_fix-xlator.md, docs/03_server/10_integration/04_gateways-and-streamers/05_customisation.md, docs/03_server/10_integration/04_gateways-and-streamers/06_examples.md, docs/03_server/10_integration/04_gateways-and-streamers/_category_.yml, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/01_introduction.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/02_streamer.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/03_streamer-client.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/04_fix-xlator.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/05_customisation.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/06_examples.md, versioned_docs/version-2022.3/03_server/10_integration/04_gateways-and-streamers/_category_.yml, versioned_docs/version-2022.4/03_server/10_integration/04_gateways-and-streamers/01_introduction.md, versioned_docs/version-2022.4/03_server/10_integration/04_gateways-and-streamers/02_streamer.md, versioned_docs/version-2022.4/03_server/10_integration/04_gateways-and-streamers/03_streamer-client.md, versioned_docs/version-2022.4/03_server/10_integration/04_gateways-and-streamers/04_fix-xlator.md, versioned_docs/version-2022.4/03_server/10_integration/04_gateways-and-streamers/05_customisation.md, versioned_docs/version-2022.4/03_server/10_integration/04_gateways-and-streamers/06_examples.md, versioned_docs/version-2022.4/03_server/10_integration/04_gateways-and-streamers/_category_.yml, versioned_docs/version-2023.1/03_server/10_integration/04_gateways-and-streamers/01_introduction.md, versioned_docs/version-2023.1/03_server/10_integration/04_gateways-and-streamers/02_streamer.md, versioned_docs/version-2023.1/03_server/10_integration/04_gateways-and-streamers/03_streamer-client.md, versioned_docs/version-2023.1/03_server/10_integration/04_gateways-and-streamers/04_fix-xlator.md, versioned_docs/version-2023.1/03_server/10_integration/04_gateways-and-streamers/05_customisation.md, versioned_docs/version-2023.1/03_server/10_integration/04_gateways-and-streamers/06_examples.md, versioned_docs/version-2023.1/03_server/10_integration/04_gateways-and-streamers/_category_.yml
should improve ChatAI answer on integration with external database
PTL-813
Yes
Yes 
No 
**This week's exciting excerpt from …
=> PTL-813: SMALL CHANGES TO FIX

docs/01_getting-started/02_quick-start/02_create-a-new-project.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/02_create-a-new-project.md
PTL-795
Docs and 2023.1
N/A
No …
=> Update genx commands

docs/01_getting-started/02_quick-start/02_create-a-new-project.md, versioned_docs/version-2023.1/01_getting-started/02_quick-start/02_create-a-new-project.md
=> PTL-795: Update quick start

docusaurus.config.js, src/css/custom.css
=> add chatbot to docs website

docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.3/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.4/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
small changes. should help to improve answers to AI questions
P806
all EXCEPT next, which has a separate section for remap
no links changes: build successful
nein
- We have an [external …
=> PTL:806: remap

docs/01_getting-started/06_developer-training/03_training-content-day3.md, docs/01_getting-started/06_developer-training/04_training-content-day4.md, docs/01_getting-started/06_developer-training/05_training-content-day5.md, docusaurus.config.js, versioned_docs/version-2023.1/01_getting-started/06_developer-training/03_training-content-day3.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/04_training-content-day4.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/05_training-content-day5.md
=> feat: Changing feedback to GitHub Issue & DevTraining quick wins (PTL-822)

docs/01_getting-started/06_developer-training/01_training-content-day1.md, versioned_docs/version-2022.3/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.4/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/01_training-content-day1.md
=> Quick fix on developer training noticed by Harry

docs/03_server/04_event-handler/03_advanced.md, versioned_docs/version-2022.3/03_server/04_event-handler/03_advanced.md, versioned_docs/version-2022.4/03_server/04_event-handler/03_advanced.md, versioned_docs/version-2023.1/03_server/04_event-handler/03_advanced.md
PTL-834
All versions
N/A
This is an attempt to improve AI knowledge base. …
=> PTL-834: Adding a description to example to improve AI.

docs/03_server/03_request-server/02_basics.md, docs/03_server/03_request-server/03_advanced.md, docs/03_server/03_request-server/04_examples.md, static/examples/requestserver/_reqrep1.md, static/examples/requestserver/_reqrep2.md, static/examples/requestserver/_reqrep3.md, versioned_docs/version-2023.1/03_server/03_request-server/02_basics.md, versioned_docs/version-2023.1/03_server/03_request-server/03_advanced.md, versioned_docs/version-2023.1/03_server/03_request-server/04_examples.md
PTL-845
only for 2023 and docs.
N/A
No. …
=> PTL-845: Create an example repository

docs/02_database/01_fields-tables-views/01_fields/01_fields-basics.md
=> PTL-848 Document on DisplayDefaultSensitiveFields

docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.3/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
PTL-837
No - only _next_
Yes
No …
=> PTL-837: updates to Server commands

docs/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2022.3/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2022.4/01_getting-started/07_glossary/01_glossary.md, versioned_docs/version-2023.1/01_getting-started/07_glossary/01_glossary.md
=> PTL-854: glossary change to Akka

docs/03_server/10_integration/10_apache-camel/01_introduction.md, versioned_docs/version-2022.3/03_server/10_integration/10_apache-camel/01_introduction.md, versioned_docs/version-2022.4/03_server/10_integration/10_apache-camel/01_introduction.md, versioned_docs/version-2023.1/03_server/10_integration/10_apache-camel/01_introduction.md
=> Gg/ptl 843 - Add more descriptions to camel integrations

docs/03_server/10_integration/08_data-pipeline/02_basics.md
https://genesisglobal.atlassian.net/browse/PLAT-831
Yes
Yes
No
LISTS. …
=> PLAT-831: Add Data Pipeline All Or Nothing error strategy

docs/03_server/10_integration/10_apache-camel/01_introduction.md, versioned_docs/version-2022.3/03_server/10_integration/10_apache-camel/01_introduction.md, versioned_docs/version-2022.4/03_server/10_integration/10_apache-camel/01_introduction.md, versioned_docs/version-2023.1/03_server/10_integration/10_apache-camel/01_introduction.md
=> improving data consumption from email description

docs/05_operations/02_commands/04_Genx_CLI.md, versioned_docs/version-2023.1/05_operations/02_commands/04_Genx_CLI.md
quick fix in Genx page
2023.1
N/A
N/A …
=> fix old files committed

docs/04_web/02_web-components/02_grids/01_grid-pro/2-connected-data.md, versioned_docs/version-2022.3/04_web/02_web-components/02_grids/01_grid-pro/2-connected-data.md, versioned_docs/version-2022.4/04_web/02_web-components/02_grids/01_grid-pro/2-connected-data.md, versioned_docs/version-2023.1/04_web/02_web-components/02_grids/01_grid-pro/2-connected-data.md
No Ticket
docs and 2023.1
N/A
No …
=> quick fix grid pro

docs/01_getting-started/05_advanced-learning/server-runtime-environment/00_classpaths.md, docs/01_getting-started/05_advanced-learning/server-runtime-environment/_category_.yml
=> feat: Added classpaths document to advanced learning

docs/01_getting-started/05_advanced-learning/server-runtime-environment/00_classpaths.md, docs/05_operations/11_release-notes/02_Version-2022.4.md
=> PTL-874: syntax error causing a build error in next

docs/03_server/10_integration/10_apache-camel/01_introduction.md
PTL-870
NEXT ONLY
DEFINITELY!
HAPPY FRIDAY …
=> Ptl 870 extra

docs/03_server/10_integration/08_data-pipeline/01_introduction.md, docs/03_server/10_integration/08_data-pipeline/02_basics.md, docs/05_operations/02_commands/04_Genx_CLI.md, versioned_docs/version-2022.3/03_server/10_integration/08_data-pipeline/01_introduction.md, versioned_docs/version-2022.3/03_server/10_integration/08_data-pipeline/02_basics.md, versioned_docs/version-2022.4/03_server/10_integration/08_data-pipeline/01_introduction.md, versioned_docs/version-2022.4/03_server/10_integration/08_data-pipeline/02_basics.md, versioned_docs/version-2023.1/03_server/10_integration/08_data-pipeline/01_introduction.md, versioned_docs/version-2023.1/03_server/10_integration/08_data-pipeline/02_basics.md, versioned_docs/version-2023.1/05_operations/02_commands/04_Genx_CLI.md
=> PTL-879: the lost edits to Data Pipeline

docs/03_server/09_inter-process-messages/03_type-safe-messages.md
Reverts genesiscommunitysuccess/docs#1304
=> Revert "PTL-882 remove link that causes build fail"

docs/05_operations/11_release-notes/01_Version-2023.1.md, docs/05_operations/11_release-notes/02_Version-2022.4.md, docs/05_operations/11_release-notes/03_Version-2022.3.md, docs/05_operations/11_release-notes/04_Version-2022.2.md, docs/05_operations/11_release-notes/05_Version-2022.1.md, versioned_docs/version-2022.3/05_operations/10_release-notes/01_Version-2022.3.md, versioned_docs/version-2022.3/05_operations/10_release-notes/02_Version-2022.2.md, versioned_docs/version-2022.3/05_operations/10_release-notes/03_Version-2022.1.md, versioned_docs/version-2022.4/05_operations/11_release-notes/01_Version-2022.4.md, versioned_docs/version-2022.4/05_operations/11_release-notes/02_Version-2022.3.md, versioned_docs/version-2022.4/05_operations/11_release-notes/03_Version-2022.2.md, versioned_docs/version-2022.4/05_operations/11_release-notes/04_Version-2022.1.md, versioned_docs/version-2023.1/05_operations/11_release-notes/01_Version-2023.1.md, versioned_docs/version-2023.1/05_operations/11_release-notes/02_Version-2022.4.md, versioned_docs/version-2023.1/05_operations/11_release-notes/03_Version-2022.3.md, versioned_docs/version-2023.1/05_operations/11_release-notes/04_Version-2022.2.md, versioned_docs/version-2023.1/05_operations/11_release-notes/05_Version-2022.1.md
=> feat: Adding the supported GSF and FUI versions on Release Notes (PTL-894)

docs/02_database/08_database-technology/03_sql.md, docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-2022.3/02_database/08_database-technology/03_sql.md, versioned_docs/version-2022.4/02_database/08_database-technology/03_sql.md, versioned_docs/version-2023.1/02_database/08_database-technology/03_sql.md, versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
=> Wjh/ptl 844: Database Technology/SQL edits for clarity

docs/01_getting-started/10_web-training/02_web-training-day2.md, versioned_docs/version-2023.1/01_getting-started/10_web-training/02_web-training-day2.md
=> quick fix on web training

versioned_docs/version-2023.1/05_operations/02_commands/01_server-commands.md
=> 2023.1 only

docs/03_server/04_event-handler/03_advanced.md, versioned_docs/version-2022.3/03_server/04_event-handler/03_advanced.md, versioned_docs/version-2022.4/03_server/04_event-handler/03_advanced.md, versioned_docs/version-2023.1/03_server/04_event-handler/03_advanced.md
PTL-807
YES
YES
TO BE REVIEWED INITIALLY BY @jay-taylerson 
LISTS. …
=> Automatic auditing with Java Event Handlers

docs/03_server/04_event-handler/06_testing.md, versioned_docs/version-2022.3/03_server/04_event-handler/06_testing.md, versioned_docs/version-2022.4/03_server/04_event-handler/06_testing.md, versioned_docs/version-2023.1/03_server/04_event-handler/06_testing.md
=> PTL-851 clarity for AI answer

docs/04_web/07_deploying/01_introduction.md, versioned_docs/version-2022.3/04_web/07_deploying/01_introduction.md, versioned_docs/version-2022.4/04_web/07_deploying/01_introduction.md, versioned_docs/version-2023.1/04_web/07_deploying/01_introduction.md
=> PTL-907 add a highlight in the code for clarity

versioned_docs/version-2023.1/04_web/05_micro-front-ends/05_foundation-login/05_foundation-login.md
2023.1
yes
bringing from docs to 2023.1 …
=> bring from next version to current version

docs/04_web/02_web-components/01_form/02_checkbox.md, versioned_docs/version-2022.4/04_web/02_web-components/01_form/02_checkbox.md, versioned_docs/version-2022.4/04_web/02_web-components/01_form/03_combobox.md, versioned_docs/version-2023.1/04_web/02_web-components/01_form/02_checkbox.md, versioned_docs/version-2023.1/04_web/02_web-components/01_form/03_combobox.md
=> PTL-931: Improve checkbox documentation

docs/04_web/02_web-components/01_form/10_select.md, versioned_docs/version-2022.4/04_web/02_web-components/01_form/09_select.md, versioned_docs/version-2023.1/04_web/02_web-components/01_form/09_select.md
=> PTL-930: Improving select documentation

docs/04_web/02_web-components/01_form/01_button.md, versioned_docs/version-2022.4/04_web/02_web-components/01_form/01_button.md, versioned_docs/version-2023.1/04_web/02_web-components/01_form/01_button.md
PTL-934
N/A
Happy weekend everybody!
LISTS. …
=> PTL-934: Improve button documentation

versioned_docs/version-2023.1/03_server/05_access-control/03_password-authentication.md
PTL-947
Yes: error is only 23.1
Builds correctly
No
LISTS. Only use …
=> simple change in the example to avoid confusion

docs/04_web/02_web-components/03_interaction/04_dialog.md, docs/04_web/02_web-components/03_interaction/07_menu.md, docs/04_web/02_web-components/03_interaction/08_modal.md, versioned_docs/version-2022.4/04_web/02_web-components/03_interaction/04_dialog.md, versioned_docs/version-2022.4/04_web/02_web-components/03_interaction/08_modal.md, versioned_docs/version-2023.1/04_web/02_web-components/03_interaction/04_dialog.md, versioned_docs/version-2023.1/04_web/02_web-components/03_interaction/09_modal.md
PTL-938
docs, 2023.1 and 2022.4
N/A
No …
=> PTL-938: Improve modal/dialog documentation

docs/04_web/02_web-components/03_interaction/11_tree-view.md, versioned_docs/version-2023.1/04_web/02_web-components/03_interaction/12_tree-view.md
=> PTL-941: improved tree-view documentation

docs/01_getting-started/06_developer-training/04_training-content-day4.md, versioned_docs/version-2023.1/01_getting-started/06_developer-training/04_training-content-day4.md
=> quick fix in developer training

docs/04_web/02_web-components/01_form/03_combobox.md, versioned_docs/version-2023.1/04_web/02_web-components/01_form/03_combobox.md
[PA-759](https://genesisglobal.atlassian.net/browse/PA-759)
Yes
N/A
No
=> PA-759 - Update combobox docs with new attributes

versioned_docs/version-2023.1/05_operations/11_release-notes/01_Version-2023.1.md
Reverts genesiscommunitysuccess/docs#1365
=> Revert "Trial update."

docs/02_database/05_database-interface/01_entitydb.md, docs/02_database/07_types-of-api/00_index.md, docs/02_database/07_types-of-api/01_async.md, docs/02_database/07_types-of-api/02_blocking.md, docs/02_database/07_types-of-api/03_rxjava.md
=> feat: document sync entity db

docs/05_operations/08_metrics/01_metrics.md
PTL-976
No
Yes
LISTS. Only use numbered lists when the sequence is important. Usually, that is a set of instructions. …
=> feat: Docs for new metrics library. (PTL-976)

docs/04_web/04_integrations/02_angular.md, versioned_docs/version-previous/04_web/04_integrations/02_angular.md
=> feat: Update integration docs for angular - PTL-999

docs/03_server/02_data-server/02_basics.md, versioned_docs/version-previous/03_server/02_data-server/02_basics.md
=> PTL-1009 Typos

docs/05_operations/03_clustering/01_overview.md, versioned_docs/version-previous/05_operations/03_clustering/01_overview.md
=> PTL-1006 Akka

docs/03_server/10_integration/06_notify/01_configuring.md, docs/03_server/10_integration/06_notify/02_email.md, docs/03_server/10_integration/06_notify/03_symphony.md, versioned_docs/version-previous/03_server/10_integration/06_notify/02_email.md
No  - bu one typo in Previous
yes
no
- Present …
=> PTL-1011 Notify example with Symphony and Email

docs/03_server/05_access-control/02_authentication-overview.md
=> Detailed authentication workflow

docs/01_getting-started/06_developer-training/00_training-intro.md, docs/01_getting-started/06_developer-training/04_training-content-day4.md, docs/01_getting-started/06_developer-training/05_training-content-day5.md
=> feat: Minor training changes (PTL-1001)

docs/01_getting-started/10_web-training/01_web-training-day1.md, versioned_docs/version-previous/01_getting-started/10_web-training/01_web-training-day1.md
=> Gui war patch 1

docs/01_getting-started/10_web-training/00_web-training-intro.md, docs/01_getting-started/10_web-training/04_web-training-day4.md, versioned_docs/version-previous/01_getting-started/10_web-training/04_web-training-day4.md
=> feat: Adding WebTraining GSF7 and FUI 14.101.1 (PTL1001)

docs/02_database/01_fields-tables-views/02_tables/02_tables-advanced.md, docs/03_server/01_configuring-runtime/02_system-definitions.md, docs/05_operations/02_commands/01_server-commands.md
=> Support for sequences on SQL databases (GSF-575)

docs/03_server/02_data-server/03_advanced.md, versioned_docs/version-previous/03_server/02_data-server/03_advanced.md
=> Changes to address issue #1385 https://github.com/genesiscommunitysuccess/docs/issues/1385

docusaurus.config.js
=> fix: Fixing head links on docs (PTL-1018)

docs/03_server/10_integration/04_gateways-and-streamers/01_introduction.md, docs/03_server/10_integration/04_gateways-and-streamers/02_fix-gateway.md, docs/03_server/10_integration/04_gateways-and-streamers/03_streamer.md, docs/03_server/10_integration/04_gateways-and-streamers/04_streamer-client.md, docs/03_server/10_integration/04_gateways-and-streamers/05_fix-xlator.md, docs/03_server/10_integration/04_gateways-and-streamers/06_customisation.md, docs/03_server/10_integration/04_gateways-and-streamers/07_examples.md
=> Added documentation for FIX gateway configuaration

docs/03_server/10_integration/04_gateways-and-streamers/02_fix-gateway.md
=> Correct typos from bad find/replace

docs/01_getting-started/10_web-training/04_web-training-day4.md, versioned_docs/version-previous/01_getting-started/10_web-training/04_web-training-day4.md
=> feat: Adding DSC to WebTraining Day4 (PTL-1001)

docs/01_getting-started/10_web-training/04_web-training-day4.md, versioned_docs/version-previous/01_getting-started/10_web-training/04_web-training-day4.md
=> fix: Fixing WebTraining Day4 DSC link (PTL-1001)

docs/04_web/05_micro-front-ends/03_foundation-header/03_foundation-header.md, versioned_docs/version-previous/04_web/05_micro-front-ends/03_foundation-header/03_foundation-header.md
=> PTL-1015 remove unnecessary number from page

docs/02_database/01_fields-tables-views/02_tables/02_tables-advanced.md, versioned_docs/version-previous/02_database/01_fields-tables-views/02_tables/02_tables-advanced.md
y
it builds
will copy to Previous after @jay taylerson has had a look at this one
Use the present tense wherever possible. Only use another …
=> PTL-1014 improve subtable documentation

docs/03_server/03_request-server/02_basics.md, versioned_docs/version-previous/03_server/03_request-server/02_basics.md
=> PTL-1039: Improve Request Reply examples with derived fields

docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-previous/05_operations/02_commands/01_server-commands.md
=> PTL-1048 and 49

docs/01_getting-started/09_server_training/00_ssdt-intro.md, docs/01_getting-started/09_server_training/00_z_ssdt-getting_started.md, versioned_docs/version-previous/01_getting-started/09_server_training/00_ssdt-intro.md, versioned_docs/version-previous/01_getting-started/09_server_training/00_z_ssdt-getting_started.md
=> fix: Adding properly GSF and FUI versions (PTL-1050)

docs/02_database/01_fields-tables-views/02_tables/01_tables-basics.md, docs/02_database/01_fields-tables-views/02_tables/02_tables-advanced.md, docs/02_database/01_fields-tables-views/02_tables/03_tables-examples.md
=> PTL-1054: better text and examples for sequence and autoincrement

docs/02_database/01_fields-tables-views/02_tables/02_tables-advanced.md
=> PTL-493 / 1054 Final change to the text 

docs/01_getting-started/06_developer-training/0a_fundaments.md, versioned_docs/version-previous/01_getting-started/06_developer-training/0a_fundaments.md
=> PTL-1057: Update fundamentals

docs/03_server/05_access-control/02_authentication-overview.md, docs/03_server/05_access-control/03_password_authentication.md, versioned_docs/version-previous/03_server/05_access-control/02_authentication-overview.md, versioned_docs/version-previous/03_server/05_access-control/03_password_authentication.md
=> Fix wrong auth-preference names.

docs/04_web/02_web-components/02_grids/01_grid-pro/0-introduction.md, docs/04_web/02_web-components/02_grids/01_grid-pro/2-connected-data.md, versioned_docs/version-previous/04_web/02_web-components/02_grids/01_grid-pro/0-introduction.md, versioned_docs/version-previous/04_web/02_web-components/02_grids/01_grid-pro/2-connected-data.md
=> add reference for ag grid events and callbacks documentation

docs/02_database/02_database-concepts/04_optimistic-concurrency.md, docs/04_web/03_design-systems/05_tokens/01_colour.md, docs/05_operations/02_commands/01_server-commands.md
=> PTL-800-MON: bogus bullet removed

docs/05_operations/02_commands/03_remap.md
=> PTL-1066: skipTableDump for remap

docs/02_database/01_fields-tables-views/03_views/01_views-basics.md, versioned_docs/version-previous/02_database/01_fields-tables-views/03_views/01_views-basics.md
Yes
Yes
Please, only merge after @kievitsp approves. …
=> gg/PTL-1084: Add requirements to create views

docs/01_getting-started/09_server_training/01_ssdt-day1.md, versioned_docs/version-previous/01_getting-started/09_server_training/01_ssdt-day1.md
=> PTL-1095 No more bellows

docs/03_server/10_integration/06_notify/01_configuring.md, docs/03_server/10_integration/06_notify/03_symphony.md
No. Project structure about to change, so I'm not going to update Previous at this stage
Yes
To be checked by @tgosling-genesis 
Use the present …
=> PTL-1079 Notify improvemnts

docs/03_server/01_configuring-runtime/02_system-definitions.md, versioned_docs/version-previous/03_server/01_configuring-runtime/02_system-definitions.md
=> chore: Added documentation for new sysdef item GlobalClasspathAdditions

docs/05_operations/02_commands/02_dbmon.md, versioned_docs/version-previous/05_operations/02_commands/02_dbmon.md
=> PTL-1070 copying a record using dbmon

.github/workflows/build.yml, package.json
=> feat: Adding engines to ensure Node.js version >=20.x (PTL-1028)

docusaurus.config.js
=> feat: Adding the relevant links to the Issue raised by the docs feedback (PTL-838)

docs/05_operations/02_commands/02_dbmon.md, versioned_docs/version-previous/05_operations/02_commands/02_dbmon.md
=> PTL-1075: DbMon setSequence

docs/05_operations/02_commands/01_server-commands.md, versioned_docs/version-previous/05_operations/02_commands/01_server-commands.md
=> Change warning in SendIt to be a recommendation

package.json
=> feat: Adding prebuild task to validate npm critical vulnerabilities (PTL-1136)

docs/05_operations/01_server-setup/01_host-prepration.md
=> Remove aerospike

docs/01_getting-started/04_prerequisites/04_genx.md, docs/01_getting-started/06_developer-training/02_training-content-day2.md, docs/04_web/04_integrations/03_react.md, docs/04_web/07_deploying/03_automated-deployment.md, static/snippet/_minimun_requirement.md
=> fix: Getting Node.js >= 20.x as pre-reqs in .md files (PTL-1028)

docs/02_database/01_fields-tables-views/02_tables/01_tables-basics.mdx, docs/02_database/03_data-structures/02_indices.mdx
=> TWO FILES CHANGED

docs/04_web/02_web-components/04_presentation/06_charts.mdx, versioned_docs/version-previous/04_web/02_web-components/04_presentation/06_charts.md
=> chore: add set-up section for chart component FUI-1819

docs/02_database/02_database-concepts/01_read.mdx, docs/02_database/03_data-structures/02_indices.mdx, docs/02_database/05_database-interface/01_entitydb.mdx, docs/02_database/05_database-interface/02_generated-repositories.mdx, docs/02_database/07_types-of-api/00_index.mdx, docs/02_database/08_database-technology/01_overview.mdx, docs/02_database/08_database-technology/02_foundationdb.mdx
=> Wjh/ptl 1166 some broken anchors - a quick trial fix

docs/01_getting-started/05_advanced-learning/postgres-data-pipeline/03_declare-source.mdx, docs/01_getting-started/05_advanced-learning/postgres-data-pipeline/05_deploy.mdx, docs/01_getting-started/06_developer-training/01_training-content-day1.mdx, docs/01_getting-started/06_developer-training/02_training-content-day2.mdx, docs/01_getting-started/06_developer-training/05_training-content-day5.mdx, docs/02_database/07_types-of-api/01_async.mdx, docs/02_database/07_types-of-api/03_rxjava.mdx, docs/05_operations/01_server-setup/01_host-prepration.mdx, versioned_docs/version-previous/01_getting-started/06_developer-training/01_training-content-day1.md, versioned_docs/version-previous/01_getting-started/06_developer-training/02_training-content-day2.md, versioned_docs/version-previous/01_getting-started/06_developer-training/05_training-content-day5.md, versioned_docs/version-previous/02_database/07_types-of-api/01_async.md, versioned_docs/version-previous/05_operations/01_server-setup/01_host-prepration.md
=> PTL-1172 revisited (broken anchors in headings)

docs/03_server/07_consolidator/02_basics.mdx, docs/03_server/07_consolidator/05_configuring-runtime.mdx, versioned_docs/version-previous/03_server/07_consolidator/02_basics.md, versioned_docs/version-previous/03_server/07_consolidator/05_configuring-runtime.md
=> docs: add docs on --coldStart arg as part of arguments tag in consolidator (GSF-6101)

docs/02_database/08_database-technology/02_foundationdb.mdx, docs/03_server/12_api-reference/03_event-handler-api.mdx
More broken anchors removed or fixed
CURRENT ONLY
BUILDS CORRECTLY
NO
Use the present tense wherever possible. Only use another tense where it …
=> PTL-1172 continued

docs/03_server/04_event-handler/01_introduction.mdx, docs/03_server/04_event-handler/03_advanced.mdx, docs/03_server/10_integration/01_rest-endpoints/01_introduction.mdx, docs/03_server/10_integration/08_data-pipeline/01_introduction.mdx, docs/03_server/11_tooling/02_intellij-plugin.mdx, docs/03_server/12_api-reference/03_event-handler-api.mdx, versioned_docs/version-previous/03_server/10_integration/08_data-pipeline/01_introduction.md
I'VE INCLUDED A COUPLE OF PREVIOUS, BUT THEY ARE NOT THE POINT
YES
NO
Use the present tense wherever possible. Only use another tense where it …
=> PTL-1172 broken links

docs/02_database/01_fields-tables-views/04_genesisdao.mdx, docs/03_server/01_configuring-runtime/02_system-definitions.mdx, versioned_docs/version-previous/02_database/01_fields-tables-views/04_genesisdao.md, versioned_docs/version-previous/03_server/01_configuring-runtime/02_system-definitions.md
=> feat: bundleGeneratedClasses gradle prop and DEPLOYED_PRODUCT sys def prop

docs/02_database/01_fields-tables-views/01_fields/02_fields-advanced.mdx, docs/05_operations/02_infrastructure/01_infrastructure.mdx
Replaces a pull request with conflicts
NO
YES
NO …
=> PTL-1196 non-nullable fields

docs/04_web/03_design-systems/03_preview.mdx
=> fix: dsc link in 03_preview.mdx

docs/03_server/01_configuring-runtime/05_genesis-router.mdx, docs/03_server/11_integration/01_rest-endpoints/03_basics.mdx
…
No
Yes
The rest of the rest endpoints documentation should probably be updated to follow the same structure.
Use the present tense wherever …
=> fix: Fix dataserver REST endpoints error and improvement documentation (PTL-1204)

docs/02_database/01_fields-tables-views/01_fields/01_fields-basics.mdx, docs/02_database/01_fields-tables-views/01_fields/02_fields-advanced.mdx, docs/02_database/01_fields-tables-views/02_tables/01_tables-basics.mdx, docs/02_database/01_fields-tables-views/03_views/02_views-advanced.mdx, versioned_docs/version-previous/02_database/01_fields-tables-views/01_fields/01_fields-basics.md, versioned_docs/version-previous/02_database/01_fields-tables-views/02_tables/01_tables-basics.md, versioned_docs/version-previous/02_database/01_fields-tables-views/03_views/02_views-advanced.md
also copies yesterday's Ray Chee update to Previous
Y
Y
N …
=> PTL-1200 add details of not null to tables basics

docs/02_database/01_fields-tables-views/02_tables/02_tables-advanced.mdx
Yes
Yes
Should be added to previous version also …
=> Use different sequence for audit table from the main table, as it must be unique

docs/01_getting-started/06_developer-training/01_training-content-day1.mdx, versioned_docs/version-previous/01_getting-started/06_developer-training/01_training-content-day1.md
=> PTL-1206 - warning about https issue in Console

docs/03_server/01_configuring-runtime/02_system-definitions.mdx, versioned_docs/version-previous/03_server/01_configuring-runtime/02_system-definitions.md
Yes
N/A
I noticed that there are some differences between current and previous for that file I changed. Is it alright?
Use the present tense …
=> PTL-1052: Improve description of missing items in system definition

docs/02_database/01_fields-tables-views/05_timestamps.mdx, versioned_docs/version-previous/02_database/01_fields-tables-views/05_timestamps.md
=> PTL-1197 genesisFlake clarification

docs/03_server/02_data-server/02_basics.mdx, docs/03_server/03_request-server/02_basics.mdx, docs/03_server/04_event-handler/02_basics.mdx, docs/03_server/07_consolidator/02_basics.mdx, docs/03_server/08_evaluator/02_basics.mdx, static/snippet/_LOG.md, versioned_docs/version-previous/03_server/02_data-server/02_basics.md, versioned_docs/version-previous/03_server/03_request-server/02_basics.md, versioned_docs/version-previous/03_server/04_event-handler/02_basics.md, versioned_docs/version-previous/03_server/07_consolidator/02_basics.md, versioned_docs/version-previous/03_server/08_evaluator/02_basics.md
=> PTL-1091: Insert description on how to use the class LOG.

docs/01_getting-started/09_server_training/03_ssdt-day3.mdx, docs/01_getting-started/10_web-training/03_web-training-day3.mdx, docs/03_server/02_data-server/02_basics.mdx, docs/03_server/04_event-handler/01_introduction.mdx, docs/03_server/04_event-handler/03_advanced.mdx, docs/03_server/04_event-handler/07_java-event-handlers.mdx, docs/03_server/05_access-control/08_authorisation-overview.mdx, docs/03_server/11_integration/07_custom-endpoints/02_basics.mdx, docs/03_server/13_api-reference/03_event-handler-api.mdx, versioned_docs/version-previous/01_getting-started/09_server_training/03_ssdt-day3.md, versioned_docs/version-previous/01_getting-started/10_web-training/03_web-training-day3.md, versioned_docs/version-previous/03_server/02_data-server/02_basics.md, versioned_docs/version-previous/03_server/04_event-handler/03_advanced.md, versioned_docs/version-previous/03_server/04_event-handler/07_java-event-handlers.md, versioned_docs/version-previous/03_server/12_api-reference/03_event-handler-api.md
=> PTL-1166: some broken anchors

README.md
=> fix: Fixing README typos and adding npm run serve (PTL-1211)

docs/05_operations/13_project-structure/03_settings-plugin.mdx
=> feat: gradle configuration cache compatibility

docs/05_operations/14_release-notes/03_migration-7-7-dot-one.mdx
=> Add migration documentation for module definition changes

docs/01_getting-started/09_server_training/01_ssdt-day1.mdx, versioned_docs/version-previous/01_getting-started/09_server_training/01_ssdt-day1.md
=> PTL-1111: Add context eventhandler to the server training static

docs/01_getting-started/01_learn-the-basics/06_building-the-database.mdx, versioned_docs/version-previous/01_getting-started/01_learn-the-basics/06_building-the-database.md
=> PTL-1219: simple removal of repeated text

docs/01_getting-started/02_quick-start/00_hardware-and-software.mdx
This is to enrich how users should check the software version installed.
We have a few cases where users are being mislead by the fact they have multiple installations of java/node etc.
=> enriched instructions to check tooling version

docs/04_web/04_integrations/02_Angular/01_getting-started.md
Only current
Yes
During testing integration examples, we noticed an error in the documentation (incorrect markup) - on left side fixed version
additionally, I added one more step in angular/getting-started (to make it consistent with the React version)
**This week's exciting excerpts from the style …
=> fix: Fix code block + add step navigate

docs/01_getting-started/04_prerequisites/02_installing-wsl.mdx, docs/01_getting-started/04_prerequisites/04_genx.mdx, docs/02_database/08_database-technology/01_overview.mdx, docs/03_server/01_configuring-runtime/02_system-definitions.mdx, docs/03_server/01_configuring-runtime/08_setting-the-database-technology.mdx, docs/05_operations/02_infrastructure/01_infrastructure.mdx, versioned_docs/version-previous/01_getting-started/04_prerequisites/02_installing-wsl.md, versioned_docs/version-previous/01_getting-started/04_prerequisites/04_genx.md, versioned_docs/version-previous/03_server/01_configuring-runtime/02_system-definitions.md
Y (in some cases)
BUILDS CORRECTLY
NO
- Present …
=> Wjh/ptl 1230 H2 as the default database

docs/05_operations/13_project-structure/02_simplified-structure.mdx
=> feat: update project structure docs that internal config module has been removed

docs/02_database/01_fields-tables-views/05_timestamps.mdx, versioned_docs/version-previous/02_database/01_fields-tables-views/05_timestamps.md
yes
Just one sentence added.
npm run start works
no …
=> ptl_1248: GenesisFlake records the creation time

docs/01_getting-started/06_developer-training/03_training-content-day3.mdx
=> Get eventhandler test back again

docs/03_server/05_access-control/09_authorisation.mdx, versioned_docs/version-previous/03_server/05_access-control/09_authorisation.md
Y
Usual build errors - no links changed
No
- …
=> PTL-1262 auth permissions corrections

docs/05_operations/13_project-structure/03_settings-plugin.mdx
=> Publication disabler plugin disabled by default

docs/02_database/01_fields-tables-views/01_fields/02_fields-advanced.mdx, docs/04_web/02_web-components/02_grids/01_grid-pro/0-introduction.mdx, docs/04_web/02_web-components/02_grids/01_grid-pro/5-grid-pro-renderers.mdx, versioned_docs/version-previous/04_web/02_web-components/02_grids/01_grid-pro/0-introduction.md, versioned_docs/version-previous/04_web/02_web-components/02_grids/01_grid-pro/5-grid-pro-renderers.md
1252 yes
751 only applied to current
checked - just the usual build errors
No …
=> PTL-1252 and PTL-751

docs/01_getting-started/06_developer-training/04_training-content-day4.mdx
=> adjusting state machine to new version

docs/02_database/02_database-concepts/00_index.mdx, docs/02_database/03_data-structures/00_index.mdx
=> Missing update to PTL-1074

docs/05_operations/13_project-structure/02_simplified-structure.mdx, docs/05_operations/13_project-structure/03_settings-plugin.mdx
=> feat: removed site specific internal module from simplified project structure

docs/06_operations/03_commands/02_dbmon.mdx, versioned_docs/version-previous/06_operations/02_commands/02_dbmon.md
=> PTL-1166: Broken anchors in dbmon page

docs/03_server/12_tooling/02_intellij-plugin.mdx
=> Add log level pointer in the log changing section

static/snippet/_minimum_requirement.mdx
=> chore: Replacing IntelliJ min version (IGNITE-57)

docs/05_components/doc-management/02_initial-config.mdx, docs/05_components/fix/installation.mdx
=> fix: Correct genx add commands for FIX and document manager docs

docs/06_operations/14_release-notes/02_current.mdx
=> PTL-1313: part two: last updates

.github/workflows/delete-closed-pr-branches.yml
=> feat: Adding a way to delete Branches on PR Close (PTL-1322)

.github/workflows/delete-closed-pr-branches.yml
=> Fixing the yml

docs/06_operations/03_commands/01_server-commands.md
Yes 
N/A - not changing links
No 
- Present …
=> Add in info box on expected date formats for SendIt

docs/06_operations/14_release-notes/02_current.mdx
=> PTL-1323: G8 release notes

docs/06_operations/03_commands/01_server-commands.md, docs/06_operations/03_commands/03_remap.mdx
=> PTL-1324: upsertAll for SendIt, loadData for remap

docs/01_getting-started/05_advanced-learning/index.mdx, docs/01_getting-started/06_developer-training/00_training-intro.mdx, docs/01_getting-started/09_server_training/00_ssdt-intro.mdx, docs/01_getting-started/10_web-training/00_web-training-intro.mdx, docs/01_getting-started/index.mdx, docs/06_operations/07_testing/02_integaration-testing.mdx
=> Origin/wjh/ptl 1328: divert people to Academy from the Learning pages

docs/06_operations/07_testing/02_integaration-testing.mdx
=> Fix typos in Testing page

docs/01_getting-started/02_quick-start/quick-start-create.mdx
=> typo - no ticket

docs/05_components/doc-management/doc-management-server/manual-installation.mdx
=> fix fileServerVersion

docs/01_getting-started/02_quick-start/go-to-the-next-level.mdx
=> Typo in go-to-the-next-level

docs/06_operations/14_release-notes/02_current.mdx
Part one: add June updates
NO
NO, but I shall do
No …
=> PTL-1344: prepare release notes for new docs release

docs/06_operations/04_clustering/03_consul.mdx
=> TS for stale resource map in consul

versioned_docs/version-previous/06_operations/14_release-notes/docs-release-oct-23.mdx
Tidying up after a final check
ONLY PREVIOUS
BUILD SUCCESSFUL
NO
Use the present tense wherever possible. Only use another tense where it is …
=> PTL-1344: remove unnecessary words

docs/03_server/12_tooling/02_intellij-plugin.mdx, versioned_docs/version-previous/03_server/12_tooling/02_intellij-plugin.mdx
=> PTL-1357 typo in filename

docs/02_database/01_fields-tables-views/02_views/index.mdx, versioned_docs/version-previous/02_database/01_fields-tables-views/02_views/index.mdx
=> PTL-1353 review: Quick update to the new views intro

docs/03_server/03_request-server/06_testing.mdx
=> Fix Typo: Change Data Server -> Request Server in Request Server testing docs

docs/03_server/03_request-server/03_advanced.mdx
=> Add simplified structure text to reqrep docs

docs/06_operations/14_release-notes/current.mdx
=> PTL-1356: Updates to release notes since 7th June

docs/06_operations/14_release-notes/current.mdx
=> PTL-1341-A: remove dependabot ref

docs/04_web/01_basics/01_front-end-basics.mdx, versioned_docs/version-previous/04_web/01_basics/01_front-end-basics.mdx
yes (will copy when agreed)
yes …
=> PTL:1370 registering when not using genx or create

docs/01_getting-started/09_server_training/03_ssdt-day3.mdx, docs/03_server/03_request-server/03_advanced.mdx
=> Adding clarifications regarding behavior of _FROM/_TO ranges

docs/06_operations/13_project-structure/03_settings-plugin.mdx
=> fix: nested pluginManagement block in settings plugin

docs/01_getting-started/01_learn-the-basics/01_simple-introduction.mdx, docs/03_server/02_data-server/03_advanced.mdx, versioned_docs/version-previous/01_getting-started/01_learn-the-basics/01_simple-introduction.mdx, versioned_docs/version-previous/03_server/02_data-server/03_advanced.mdx
Y
N
Will copy to PREV WHEN CHECKED
- Present …
=> PTL-1373A: Continuing issues with MAX ROWS etc

docs/06_operations/09_metrics/01_metrics.mdx
YES - will copy to previous when checked
NOT YET
NO …
=> PTL-1374: error in java code snippet in metrics/timer

docs/03_server/09_packaged-business-capabilities/01_document-generation/01_templates.mdx, docs/05_components/generated-docs/server.mdx, versioned_docs/version-previous/03_server/09_packaged-business-capabilities/01_document-generation/01_templates.mdx, versioned_docs/version-previous/05_components/generated-docs/server.mdx
YES
**_BUILDS SUCCESSFULLY_**
No …
=> PTL-1380: issue on generated docs

docs/04_web/02_web-components/02_grids/01_grid-pro/2-connected-data.mdx
Current only
BUILDS SUCCESSFULLY
NO
- Present …
=> PTL-1379: server-side and client-side connected data

docs/06_operations/14_release-notes/current.mdx
=> PTL-1378: keeps the release notes up to date

docs/06_operations/13_project-structure/03_settings-plugin.mdx
=> Settings plugin product name property

docs/06_operations/03_commands/03_remap.mdx
=> feat: RemapEnableAutoConfirm SysDef flag

docs/03_server/02_data-server/06_testing.mdx
I found a line of code was in correct in the testing documentation for dataservers so I have changed it.
No
Yes
No
Use the present tense …
=> Update 06_testing.mdx: Changed line of code in dataserver testing documentation

docs/03_server/11_integration/01_rest-endpoints/03_basics.mdx, versioned_docs/version-previous/03_server/11_integration/01_rest-endpoints/03_basics.mdx
=> PTL-1399: solves issue 1747

docs/06_operations/14_release-notes/current.mdx
CURRENT
NO CHANGES
BRINGS US UP TO DATE SO WE CAN MOVE TO 8.3 WITHOUT FUSS
Use the present tense wherever possible. Only use another tense where …
=> PTL-1406: release notes to cover 8.2 updates in August

docs/02_database/01_fields-tables-views/01_tables/01_tables-basics.mdx
=> docs(tables): adding instructions for shared fields

docs/07_how-to/15_audit.mdx, docs/07_how-to/22_web-e2e-test.mdx, docs/07_how-to/index.mdx, package-lock.json
=> PTL-1426: fix links in how to home page

docs/01_getting-started/06_developer-training/05_training-content-day5.mdx, docs/03_server/02_data-server/02_basics.mdx, docs/03_server/02_data-server/03_advanced.mdx, docs/03_server/02_data-server/06_testing.mdx, docs/03_server/03_request-server/01_introduction.mdx, docs/03_server/03_request-server/03_advanced.mdx, docs/03_server/03_request-server/06_testing.mdx, docs/03_server/04_event-handler/03_advanced.mdx, docs/03_server/04_event-handler/04_examples.mdx, docs/03_server/04_event-handler/06_testing.mdx, docs/03_server/05_access-control/08_authorisation-overview.mdx, docs/03_server/05_access-control/09_authorisation.mdx, docs/03_server/06_state-machine/03_advanced.mdx
=> feat: replace old deprecated code samples and docs related to permissioning blocks with new syntax. Required for GSF 8.3 (GSF-6924)

docs/06_operations/14_release-notes/current.mdx
=> PTL-1428: Improve layout (and wording) of the Release Notes page

docs/06_operations/14_release-notes/current.mdx
=> chore: provide fully qualified name for Injector package for consistency and clarity

docs/06_operations/13_project-structure/02_simplified-structure.mdx, versioned_docs/version-previous/06_operations/13_project-structure/02_simplified-structure.mdx
=> Added section on adding modules to simplified projects

docs/03_server/09_packaged-business-capabilities/01_document-generation/01_templates.mdx, docs/05_components/generated-docs/installation.mdx, docs/05_components/generated-docs/server.mdx, versioned_docs/version-previous/03_server/09_packaged-business-capabilities/01_document-generation/01_templates.mdx, versioned_docs/version-previous/05_components/generated-docs/installation.mdx, versioned_docs/version-previous/05_components/generated-docs/server.mdx
=> update file server package name

docs/03_server/05_access-control/09_authorisation.mdx
=> chore: adding more information around dynamic auth and ChronicleMap

docs/03_server/01_configuring-runtime/02_system-definitions.mdx
=> PTL-1431: new setting for system-definition

docs/07_how-to/index.mdx
=> PTL-1466: typo - missing space

docs/04_web/01_basics/01_front-end-basics.mdx
=> PTL-1479: typo reported

docs/07_how-to/15_audit.mdx
=> Point to repo

docs/03_server/05_access-control/03_password_authentication.mdx
=> [8.4] Add first name and last name to login response

docs/06_operations/14_release-notes/current.mdx
ONLY CURRENT
MOST CERTAINLY
NO …
=> PTL-1480: 8.4 release notes

docs/06_operations/03_commands/01_server-commands.md
=> Improve SendIt tips around dates and datetimes

docs/01_getting-started/04_prerequisites/04_genx.mdx
**No**
**Yes**
**This related to this https://github.com/genesiscommunitysuccess/blank-app-seed/pull/343, just syncing the docs with the latest changes there.**
---
Use the present tense …
=> fix: update api-host step changes from blank-app-seed - FUI-2207

docs/02_database/01_fields-tables-views/01_tables/index.mdx, docs/02_database/01_fields-tables-views/02_views/index.mdx, docs/03_server/01_configuring-runtime/02_system-definitions.mdx, docs/03_server/01_configuring-runtime/03_processes.mdx, docs/03_server/01_configuring-runtime/04_service-definitions.mdx, docs/03_server/02_data-server/02_basics.mdx, docs/03_server/03_request-server/02_basics.mdx, docs/03_server/04_event-handler/02_basics.mdx, docs/03_server/06_state-machine/02_basics.mdx, docs/03_server/07_consolidator/02_basics.mdx, docs/03_server/09_data-pipelines/02_basics.mdx
__________
CURRENT ONLY
YES
NO
=> PTL-1394: old filename locations removed

docs/07_how-to/08_kotlin.mdx, docs/07_how-to/14_ht-front-end-simple.mdx, docs/07_how-to/15_audit.mdx, docs/07_how-to/25_run-examples.mdx, docs/07_how-to/30_front-end-example.mdx, docs/07_how-to/35_alm.mdx, docs/07_how-to/index.mdx, sidebars.js
__________
Current only
Builds correctly
PLEASE DO NOT MERGE YET
=> PTL-!493: Reorg of How To, including new pages for Kotlin (in menu) and ALM (not yet in menu)

docs/03_server/09_data-pipelines/03_implementations.mdx, docs/03_server/09_data-pipelines/04_custom-components.mdx
=> feat: added docs for JMS pipeline integration (GSF-7014)

docs/03_server/09_data-pipelines/03_implementations.mdx, docs/03_server/09_data-pipelines/04_custom-components.mdx
Reverts genesiscommunitysuccess/docs#1801
=> Revert "feat: added docs for JMS pipeline integration (GSF-7014)"

docs/03_server/09_data-pipelines/03_implementations.mdx, docs/03_server/09_data-pipelines/04_custom-components.mdx
__________
current only
yessir
no
=> Typos and formatting in Data Pipelins

docs/07_how-to/08_kotlin.mdx
=> PLAT-599: typos/formatting on Kotlin doc

docs/03_server/09_data-pipelines/05_configuring-runtime.mdx
=> fix: datapipelines script name must be suffixed as: -pipelines.kts

docs/07_how-to/40_alm-app/01_getting-started.mdx, docs/07_how-to/40_alm-app/02_improving-back-end.mdx, docs/07_how-to/40_alm-app/03_improving-front-end.mdx, docs/07_how-to/40_alm-app/04_ingesting-external.mdx
=> PTL-1551links to the main code

docs/03_server/01_configuring-runtime/09_site-specific.mdx, docs/07_how-to/40_alm-app/00_index.mdx
__________
CURRENT ONLY
NOT YET
NO
=> PTL-1555: Business intro for ALM

docs/03_server/03_request-server/04_examples.mdx, docs/03_server/09_data-pipelines/02_basics.mdx, docs/03_server/11_integration/09_apache-camel/02_basics.mdx, docs/06_operations/09_metrics/03_service_metrics.mdx
=> PTL-1558: correct newly broken anchors

docs/05_components/reporting/server.mdx
=> update docs for reporting entities list change (RPT-4)

docs/06_operations/03_commands/01_server-commands.md
=> add GENESIS_LOGGING_LEVEL docs (GSF-6099)

docs/07_how-to/11_notify-email.mdx, sidebars.js
=> PTL-1557: How To for Email with attachment

docs/08_release-notes/index.mdx
=> chore: add image to v8.4 release card

docs/03_server/09_data-pipelines/03_implementations.mdx
=> feat: update camel data pipeline page (DP-25)

docs/08_release-notes/index.mdx, src/components/ReleaseCard.js, static/img/desktop.ini
=> feat: enable dynamic image URLs in component

docusaurus.config.js
=> feat: enable breadcrumbs in configuration

sidebars.js, src/css/custom.css
=> chore: change uppercase links to sentence case in sidebar menu

src/components/ReleaseCard.js, src/css/custom.css
=> fix: fix image size

src/css/custom.css
=> feat: sidebar top level item text larger

docs/03_server/index.mdx
__________
CURRENT
Have you done a trial build to check all new or YES
NO
=> PTL-1617: broken link

docs/02_database/01_fields-tables-views/01_tables/01_tables-basics.mdx, versioned_docs/version-previous/02_database/01_fields-tables-views/01_tables/01_tables-basics.mdx
__________
YES - BUT PLSE CHECK
YES
NO
=> PLAT-599: copy json removal to preprod

docs/01_getting-started/09_server_training/03_ssdt-day3.mdx, docs/03_server/02_data-server/02_basics.mdx, docs/03_server/02_data-server/03_advanced.mdx, docs/03_server/02_data-server/04_examples.mdx, docs/03_server/03_request-server/02_basics.mdx, docs/03_server/05_access-control/09_authorisation.mdx
=> feat: Change syntax of derivedField in documents to reflect version 8.5.0 (GSF-7046)

docs/03_server/09_data-pipelines/03_implementations.mdx, docs/03_server/09_data-pipelines/04_custom-components.mdx
__________
CURRENT
YES
WJH rebuild and edit of Zuhaa's original GSF-7014 pull request
=> WJH/GSF-7014: Data Pipeline updates for v8.5

docs/06_operations/14_release-notes/current.mdx
=> final 8.5 release notes.

docs/03_server/09_data-pipelines/06_examples.mdx, docs/07_how-to/07_consume-kafka.mdx, docs/07_how-to/36_ibm-mq.mdx, docs/07_how-to/36_jms.mdx, sidebars.js
=> 8.5 HOW TO RELEASE - feat: add docs for how to JMS (GSF-7009)

docs/03_server/01_configuring-runtime/02_system-definitions.mdx, docs/03_server/12_tooling/03_genesis-launcher/01_install.mdx, docs/03_server/12_tooling/03_genesis-launcher/02_running.mdx, docs/03_server/12_tooling/03_genesis-launcher/_category_.yml
=> rename launcher to start

src/css/custom.css
=> chore: hide current version badge

docs/03_server/09_data-pipelines/06_examples.mdx
=> PTL-1640: bad link and format

docs/01_getting-started/02_quick-start/go-to-the-next-level.mdx, docs/01_getting-started/06_developer-training/00_training-intro.mdx, docs/01_getting-started/09_server_training/00_ssdt-intro.mdx, docs/01_getting-started/10_web-training/00_web-training-intro.mdx, docs/01_getting-started/index.mdx, versioned_docs/version-previous/01_getting-started/02_quick-start/go-to-the-next-level.mdx, versioned_docs/version-previous/01_getting-started/06_developer-training/00_training-intro.mdx, versioned_docs/version-previous/01_getting-started/09_server_training/00_ssdt-intro.mdx, versioned_docs/version-previous/01_getting-started/10_web-training/00_web-training-intro.mdx, versioned_docs/version-previous/01_getting-started/index.mdx
=> PTL-1641: change links to academy

docs/07_how-to/40_alm-app/01_getting-started.mdx, docs/07_how-to/40_alm-app/04_ingesting-external.mdx
=> Updating docs with latest links

docs/05_components/doc-management/doc-management-server/configuring-file-manager.mdx
=> add ability to configure s3 minimum multipart upload size (DOCMGMT-46)

docs/001_develop/03_client-capabilities/008_interaction/text-area.mdx, examples/ui/client-capabilities/interaction/text-area.js
=> docs: ui capabilities text area PTL-1580

docs/001_develop/03_client-capabilities/008_interaction/checkbox.mdx, docs/001_develop/03_client-capabilities/008_interaction/text-field.mdx
Also fixes rendering issue in the text field file
=> docs: update checkbox page to new style PTL-1569

docs/001_develop/03_client-capabilities/008_interaction/stepper.mdx, examples/ui/client-capabilities/interaction/stepper.js
=> docs: ui capabilities stepper PTL-1578

docs/001_develop/02_server-capabilities/011_integrations-data-pipelines/index.mdx
=> pipelines page edits

docs/03_server/01_configuring-runtime/02_system-definitions.mdx
=> feat: configurable update frequency for cluster db strategy (GSF-7005)

docs/001_develop/02_server-capabilities/index.mdx
=> fix: remove duplicated index file

docs/001_develop/03_client-capabilities/006_charts/002_g2plot-chart/01_chart-types.mdx, docs/001_develop/03_client-capabilities/006_charts/002_g2plot-chart/02_chart-datasource.mdx, docs/001_develop/03_client-capabilities/006_charts/002_g2plot-chart/03_chart_html_api.mdx, docs/001_develop/03_client-capabilities/007_forms/002_smart-forms/08_html_api.mdx
=> docs: HTML API changes for charts/forms PTL-1521

docs/001_develop/03_client-capabilities/021_desktop-interoperability/005_listen_intent.mdx
=> PTL-1624 - Intent listener

docs/001_develop/03_client-capabilities/008_interaction/number-field.mdx, examples/ui/client-capabilities/interaction/number-field.js
=> docs: ui capabilities number field PTL-1571

docusaurus.config.js
=> fix: build issue workaround PTL-0

docs/001_develop/03_client-capabilities/020_internationalization/index.mdx
=> docs: fix broken fdc3 page link - PTL-1544

docs/001_develop/03_client-capabilities/007_forms/003_form-inputs/combobox.mdx, docs/001_develop/03_client-capabilities/007_forms/003_form-inputs/select.mdx, docs/001_develop/03_client-capabilities/008_interaction/listbox.mdx, examples/ui/client-capabilities/interaction/listbox.js
* Adds docs and live example for listbox
* Fixes some small errors in other docs where they were referencing microsoft's packages rather than our web-core
=> docs: listbox primitive component docs PTL-1593

docs/001_develop/03_client-capabilities/009_presentation/badge.mdx, docs/001_develop/03_client-capabilities/009_presentation/examples/badge.js, src/css/custom.css
=> docs: ui capabilities badge PTL-1601

docs/001_develop/03_client-capabilities/009_presentation/banner.mdx, docs/001_develop/03_client-capabilities/009_presentation/examples/banner.js
=> docs: ui capabilities banner PTL-1602

docs/001_develop/03_client-capabilities/009_presentation/card.mdx, docs/001_develop/03_client-capabilities/009_presentation/examples/card.js
=> docs: ui capabilities card PTL-1605

docs/001_develop/03_client-capabilities/009_presentation/connection-indicator.mdx, docs/001_develop/03_client-capabilities/009_presentation/examples/connection-indicator.js
=> docs: ui capabilities connection-indicator PTL-1607

docs/001_develop/03_client-capabilities/009_presentation/disclosure.mdx, docs/001_develop/03_client-capabilities/009_presentation/examples/disclosure.js
=> docs: ui capabilities disclosure PTL-1608

docs/001_develop/03_client-capabilities/009_presentation/divider.mdx, docs/001_develop/03_client-capabilities/009_presentation/examples/divider.js
=> docs: ui capabilities divider PTL-1609

docs/001_develop/03_client-capabilities/008_interaction/modal.mdx, docs/001_develop/03_client-capabilities/008_interaction/tabs.mdx, docs/001_develop/03_client-capabilities/008_interaction/tree-view.mdx, examples/ui/client-capabilities/interaction/tree-view.js
* Docs for tree and tree view
* Some tiny tweaks for modal and tabs
=> docs: tree view primitive docs PTL-1598

docs/001_develop/03_client-capabilities/005_grids/003_grid-pro/index.mdx
=> docs: remove external or invalid links from grid-pro docs - PTL-1517

docs/001_develop/03_client-capabilities/009_presentation/examples/icon.js, docs/001_develop/03_client-capabilities/009_presentation/icon.mdx
=> docs: ui capabilities icon PTL-1611

docs/001_develop/03_client-capabilities/009_presentation/examples/progress-ring.js, docs/001_develop/03_client-capabilities/009_presentation/progress-ring.mdx
=> docs: progress ring PTL-1612

docs/001_develop/03_client-capabilities/003_login/_category_.yml, docs/001_develop/03_client-capabilities/003_login/index.mdx, docs/001_develop/03_client-capabilities/004_header/index.mdx
=> docs: foundation-login PTL-1506

docs/001_develop/03_client-capabilities/009_presentation/examples/card.js
Fix reference to alpha button in card example
=> fix: reference to alpha button PTL-0

docs/001_develop/03_client-capabilities/008_interaction/dropdown-menu.mdx, docs/001_develop/03_client-capabilities/008_interaction/menu.mdx, docs/001_develop/03_client-capabilities/009_presentation/examples/avatar.js, docs/001_develop/03_client-capabilities/009_presentation/examples/badge.js, docs/001_develop/03_client-capabilities/009_presentation/examples/banner.js, docs/001_develop/03_client-capabilities/009_presentation/examples/breadcrumb.js, docs/001_develop/03_client-capabilities/009_presentation/examples/connection-indicator.js, docs/001_develop/03_client-capabilities/009_presentation/examples/disclosure.js, docs/001_develop/03_client-capabilities/009_presentation/examples/divider.js, docs/001_develop/03_client-capabilities/009_presentation/examples/horizontal-scroll.js, docs/001_develop/03_client-capabilities/009_presentation/examples/progress-ring.js, docs/001_develop/03_client-capabilities/009_presentation/examples/progress.js, examples/ui/client-capabilities/filters/filters.js, examples/ui/client-capabilities/interaction/accordion.js, examples/ui/client-capabilities/interaction/criteria-segmented-control.js, examples/ui/client-capabilities/interaction/number-field.js, examples/ui/client-capabilities/interaction/segmented-control.js, examples/ui/client-capabilities/interaction/text-area.js, examples/ui/client-capabilities/interaction/text-field.js, examples/ui/client-capabilities/interaction/tooltip.js
=> fix: replace -webkit-fill-available (PTL-1568)

docs/001_develop/03_client-capabilities/024_testing/_category_.yml, docs/001_develop/03_client-capabilities/024_testing/docs/_category_.yml, docs/001_develop/03_client-capabilities/024_testing/index.mdx
=> docs: foundation testing PTL-1688

docs/001_develop/02_server-capabilities/002_data-model/index.mdx
=> add docs for reusing lambdas in derived fields for views (GSF-7082)

docusaurus.config.js
=> fix: add webpack alias for foundationZero/ZeroDesignSystem

docs/001_develop/03_client-capabilities/014_utility-methods/02_env-util.mdx
=> docs: environment utilities PTL-1691

docs/001_develop/03_client-capabilities/014_utility-methods/04_logger-util.mdx
=> docs: logger utility PTL-1694

src/components/Card.js
=> docs: fix links in old cards

docs/001_develop/03_client-capabilities/014_utility-methods/13_uuid-util.mdx, docs/001_develop/03_client-capabilities/022_framework-integration/003_integration-react.mdx
=> docs: uuid utilities PTL-1701

examples/ui/client-capabilities/interaction/stepper.css, examples/ui/client-capabilities/interaction/stepper.js
=> fix: fix stepper example 

docs/001_develop/03_client-capabilities/002_server-communications/04_credential-manager.mdx, docs/001_develop/03_client-capabilities/002_server-communications/05_datasource.mdx, docs/001_develop/03_client-capabilities/002_server-communications/06_metadata.mdx, docs/001_develop/03_client-capabilities/002_server-communications/07_session.mdx, docs/001_develop/03_client-capabilities/002_server-communications/08_storage.mdx, docs/001_develop/03_client-capabilities/002_server-communications/09_testing.mdx, docs/001_develop/03_client-capabilities/002_server-communications/10_user.mdx, docs/001_develop/03_client-capabilities/002_server-communications/11_utils.mdx
=> UI headings review

docs/001_develop/03_client-capabilities/003_login/index.mdx, docs/001_develop/03_client-capabilities/005_grids/002_entity-manager/01_entity-manager-grid.mdx, docs/001_develop/03_client-capabilities/005_grids/002_entity-manager/02_entity-manager-form.mdx, docs/001_develop/03_client-capabilities/005_grids/002_entity-manager/index.mdx, docs/001_develop/03_client-capabilities/015_layout-management/10_foundation-layout.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/01_foundation-fdc3.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/01_foundation-openfin.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/openfin/01_foundation-openfin.mdx
=> Removing references to low-code

docs/001_develop/01_development-environment/003_genesis-start/index.mdx
=> Move Genesis Start to version 0.1.6

docs/004_release-notes/001_platform/8/8.1.mdx, docs/004_release-notes/001_platform/8/8.2.mdx, docs/004_release-notes/001_platform/8/8.3.mdx, docs/004_release-notes/001_platform/8/8.4.mdx, docs/004_release-notes/001_platform/8/8.5.mdx, docs/004_release-notes/001_platform/8/8.6.mdx, docs/004_release-notes/index.mdx
=> PTL-1710: RELEASE NOTES FOR 8.6

src/components/Card/Card.css, src/components/Card/CardList.js, src/components/LiveExampleBuilder.js
Fixes small regression introduced in https://github.com/genesiscommunitysuccess/docs/pull/2022 which effected live example cards
=> fix: regression with card styling for web live examples PTL-0

docs/001_develop/02_server-capabilities/004_real-time-queries-data-server/index.mdx, docs/001_develop/02_server-capabilities/005_snapshot-queries-request-server/index.mdx
=> fix client api json in data server and request server pages

docs/001_develop/01_development-environment/002_launchpad/index.mdx
=> fix: correct log location for launchpad projects

docs/004_release-notes/001_platform/8/8.0.mdx
=> reverse order for patch releases

src/components/ReleaseCard/ReleaseCard.css, src/components/ReleaseCard/ReleaseCard.js
Demo:
https://github.com/user-attachments/assets/475b507b-ae9b-49a2-84d8-67b88d939478
=> chore: modify ReleaseCard

docs/001_develop/01_development-environment/003_genesis-start/index.mdx
=> Update instructions to give full paths to gradle files

bootstrap-build-env.sh
=> chore: adding a script to add swap for the build

docs/002_how-to/40_alm-app/04_ingesting-external.mdx
=> ALM update CDs sample file location

docusaurus.config.js, package-lock.json, package.json, src/css/custom.css
=> Adding feedback widget

docs/002_how-to/50_ote-app/02_improving-back-end.mdx
=> PTL-1725: quick fix to OTE app

docs/002_how-to/50_ote-app/02_improving-back-end.mdx
=> PTL-1725: extra change

docs/002_how-to/20_prepare-test.mdx, docs/002_how-to/21_web-unit-test.mdx, docs/002_how-to/22_web-e2e-test.mdx, docs/002_how-to/30_front-end-example.mdx, docs/002_how-to/36_jms.mdx, docs/002_how-to/40_alm-app/00_index.mdx, docs/002_how-to/50_ote-app/00_index.mdx, docs/002_how-to/50_ote-app/03_improving-front-end.mdx
=> PTL-1644: incorrect heading in OTE front end

docs/001_develop/02_server-capabilities/008_access-control/02_authentication/index.mdx
=> Fix closure of kotlin OIDC

docs/002_how-to/01_auth.mdx, docs/002_how-to/03_join-expose.mdx, docs/002_how-to/05_ingest-csv.mdx, docs/002_how-to/07_consume-kafka.mdx, docs/002_how-to/08_kotlin.mdx, docs/002_how-to/09_fdc3.mdx, docs/002_how-to/11_notify-email.mdx, docs/002_how-to/14_ht-create-simple-page.mdx, docs/002_how-to/15_audit.mdx, docs/002_how-to/18_rest.mdx, docs/002_how-to/50_ote-app/03_improving-front-end.mdx
=> Remove : from how to titles and amend instruction for OTE form change

docs/004_release-notes/001_platform/8/8.6.mdx
=> Add release notes for 8.6.1, 8.6.2 and 8.6.3

docs/001_develop/03_client-capabilities/015_layout-management/10_foundation-layout.mdx, docs/001_develop/03_client-capabilities/015_layout-management/index.mdx, docs/001_develop/03_client-capabilities/015_layout-management/layout_02_html_api.mdx, docs/001_develop/03_client-capabilities/015_layout-management/layout_03_js_api.mdx, docs/001_develop/03_client-capabilities/015_layout-management/layout_04_items_in_layout.mdx, docs/001_develop/03_client-capabilities/015_layout-management/layout_05_binding_events_store.mdx, docs/001_develop/03_client-capabilities/015_layout-management/layout_06_examples_configs.mdx, docs/001_develop/03_client-capabilities/015_layout-management/layout_07_troubleshooting.mdx
=> Wjh/ptl 1669: Foundation Layout review

docs/001_develop/03_client-capabilities/006_charts/03_chart_html_api.mdx
Adding link to order by index to charts html page. Saves me asking in server chat.
=> Adding orderby index link in chart

docs/004_release-notes/001_platform/7/7.2.mdx, docs/004_release-notes/001_platform/8/8.2.mdx
=> Release notes for 8.2.8 and 7.2.21

docs/004_release-notes/001_platform/8/8.6.mdx
=> add 8.6.4 release notes

docs/001_develop/01_development-environment/002_launchpad/02_genesis-cloud-workspace/index.mdx, src/css/custom.css
=> Workspaces limit image sizes

docs/003_build-deploy-operate/03_operate/002_commands/index.mdx
=> 8.7.0 RELEASE: Document genesisInstallHook CLI(PTL-1685 )

docs/001_develop/03_client-capabilities/024_testing/stubs.mdx
__________
Yes
No, but there are no new internal links
No
=> docs: client foundation testing mocks PTL-1754

docs/001_develop/02_server-capabilities/007-workflow-state-machine/index.mdx, docs/001_develop/02_server-capabilities/012_custom-components/index.mdx
=> state machine + custom components edits

docs/004_release-notes/001_platform/7/7.1.mdx
=> 7.1.25 Patch notes

docs/004_release-notes/001_platform/8/8.2.mdx
=> update 8.2 release notes with 8.2.9 patch

docs/001_develop/02_server-capabilities/007-workflow-state-machine/index.mdx, docs/001_develop/03_client-capabilities/008_interaction/listbox.mdx
=> Wjh/ptl 1764: New intro for State Machine

docs/001_develop/05_glossary.mdx
=> PTL-1777 FIX definition change link

docs/004_release-notes/001_platform/8/8.6.mdx, docs/004_release-notes/001_platform/8/8.7.mdx
=> PTL-1780: release notes (patch)

docs/002_how-to/50_ote-app/03_improving-front-end.mdx
=> PTL-1779: OTE How To. Update code snippets for clarity and consistency

docs/002_how-to/50_ote-app/01_getting-started.mdx
=> PTL-1779 final changes to OTE HOW TO

docs/003_build-deploy-operate/03_operate/002_commands/index.mdx, docs/004_release-notes/001_platform/8/8.6.mdx, docs/004_release-notes/001_platform/8/8.7.mdx
=> add new purger features

docs/001_develop/01_development-environment/002_launchpad/02_genesis-cloud-workspace/index.mdx, docs/002_how-to/50_ote-app/01_getting-started.mdx, static/snippet/_common-query-fields.md
=> PTL-1781 disappearing images

docs/004_release-notes/001_platform/8/8.7.mdx
=> PTL-1786: release notes 8.7.5

docs/004_release-notes/001_platform/8/8.0.mdx, docs/004_release-notes/001_platform/8/8.2.mdx, docs/004_release-notes/001_platform/8/8.6.mdx, docs/004_release-notes/001_platform/8/8.7.mdx
=> PTL-1792: release notes 8.7.6 and 8.6.10

docs/001_develop/04_business-components/08_fix/fix-pipelines.mdx
=> fix data pipelines (FIX-173)

docs/001_develop/02_server-capabilities/011_integrations/01_data-pipelines/index.mdx
=> add missing pipeline extn functions plus GSF-7153 fix

docs/001_develop/03_client-capabilities/013_toast-notifications/index.mdx, docs/001_develop/03_client-capabilities/023_custom-components/03_state-management.mdx
__________
You for king bet
No
=> PTL-1801: the reversed change in State Management and rectifies weird changes to Toast

docs/004_release-notes/001_platform/8/8.2/index.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx
=> Adding 8.6.11 server patch release notes

docs/001_develop/03_client-capabilities/013_toast-notifications/_category_.yml, docs/001_develop/03_client-capabilities/013_toast-notifications/index.mdx
=> PTL-1801-tidying up

docs/001_develop/03_client-capabilities/010_filters/index.mdx, docs/001_develop/03_client-capabilities/013_toast-notifications/index.mdx, docs/001_develop/05_glossary.mdx
=> PTL-1794: Filter page review

docs/003_build-deploy-operate/03_operate/002_commands/index.mdx
=> PTL-1685-fix typo on install hooks directory

docs/001_develop/02_server-capabilities/015_communications/index.mdx
=> Review and update Communications page

docs/001_develop/02_server-capabilities/004_real-time-queries-data-server/index.mdx, docs/004_release-notes/001_platform/8/8.2/index.mdx, docs/004_release-notes/001_platform/8/8.5/index.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx, docs/004_release-notes/001_platform/8/8.7/index.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx
=> Add new release notes for 8.8.1, 8.7.7, 8.6.12, 8.5.6 and 8.2.13

docs/001_develop/02_server-capabilities/004_real-time-queries-data-server/index.mdx
=> PTL-1805: Waterloo. Grammar and clarity change

docs/001_develop/01_development-environment/002_launchpad/02_genesis-cloud-workspace/index.mdx
=> Image resizing

docs/001_develop/02_server-capabilities/004_real-time-queries-data-server/index.mdx, docs/002_how-to/01_auth.mdx
=> WJH/PTL-1807: link to incorrect readme

docs/001_develop/02_server-capabilities/004_real-time-queries-data-server/index.mdx, docs/001_develop/03_client-capabilities/003_login/index.mdx, docs/001_develop/03_client-capabilities/019_styling/index.mdx, docs/001_develop/03_client-capabilities/020_internationalization/index.mdx, docs/001_develop/03_client-capabilities/022_framework-integration/index.mdx, docs/002_how-to/01_auth.mdx
=> Wjh/ptl 1797: internationalization review

static/data/sidebar-items-data.json
=> PTL-1808: Blurb for Bloomberg

docs/004_release-notes/001_platform/8/8.3/index.mdx, docs/004_release-notes/001_platform/8/8.5/index.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx, docs/004_release-notes/001_platform/8/8.7/index.mdx
=> PTL-1814: first commit

docs/001_develop/03_client-capabilities/002_server-communications/02_criteria-matching.mdx
=> feat: Add criteria matching improvements added in 8.9 (GSF-7174)

docs/004_release-notes/001_platform/8/8.6/index.mdx, docs/004_release-notes/001_platform/8/8.7/index.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx
=> add release notes for GSF-7197

docs/004_release-notes/001_platform/8/8.4/index.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx
=> PTL-1814: Further updates to patch releases

docs/002_how-to/40_alm-app/00_index.mdx, docs/004_release-notes/001_platform/8/8.2/index.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx, docs/004_release-notes/001_platform/8/8.7/index.mdx
=> first commit

docs/004_release-notes/001_platform/8/8.2/index.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx
=> PTL-1817: patch releases of 21 Feb

docs/004_release-notes/001_platform/8/8.8/index.mdx
=> release 8.8.6

docs/004_release-notes/001_platform/8/8.8/index.mdx, docs/004_release-notes/001_platform/8/8.8/integrations.mdx, docs/004_release-notes/001_platform/8/8.8/notify.mdx
=> PTL-1818: patch releases for integrations and notify

docs/003_build-deploy-operate/03_operate/005_metrics/index.mdx
=> Update graphite port - genesis requires pickled port, not plaintext

docs/001_develop/03_client-capabilities/013_toast-notifications/index.mdx
=> docs: add info for styling notifications

docs/002_how-to/01_auth.mdx, docs/002_how-to/03_join-expose.mdx
=> PTL-1829: fix link

docs/001_develop/01_development-environment/002_launchpad/01_genesis-create/index.mdx, docs/001_develop/01_development-environment/002_launchpad/02_genesis-cloud-workspace/index.mdx
=> Fix gif to useBaseUrl

docs/004_release-notes/001_platform/8/8.8/index.mdx
=> adding 1 patch

docs/004_release-notes/001_platform/8/8.9/index.mdx
=> Redo 8 9 release notes

docs/001_develop/02_server-capabilities/002_data-model/index.mdx, docs/003_build-deploy-operate/01_build/004_build-tools/index.mdx
=> PTL-1835: incorrect method in example

docs/004_release-notes/001_platform/8/8.8/notify.mdx, docs/004_release-notes/001_platform/8/8.9/notify.mdx
=> PTL-1836: Notify patch releases 10 Mar

docs/001_develop/02_server-capabilities/004_real-time-queries-data-server/index.mdx
=> docs(pal-dataserver): Add maxBytesPerCharacter information to dataserver docs (GSF-7231)

docs/004_release-notes/001_platform/8/8.2/index.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx, docs/004_release-notes/001_platform/8/8.9/index.mdx
=> Latest server patches

docs/001_develop/02_server-capabilities/007-workflow-state-machine/index.mdx
=> Correct State Machine example (PTL-1867)

docs/001_develop/02_server-capabilities/017_runtime-configuration/09_genesis-router/index.mdx
=> docs(router): Add `websocketServer` and `onHeartbeatPing` sections to router documentation (PTL-1879)

docs/001_develop/03_client-capabilities/019_styling/02_direct-customization-genesis-components/03_design-system-configurator.mdx
=> fix: revert dsc path change - PA-1623

docs/001_develop/03_client-capabilities/008_interaction/modal.mdx, examples/ui/client-capabilities/interaction/modal.js
=> docs: update api docs for modal FUI-2299

docs/002_how-to/50_ote-app/02_improving-back-end.mdx
=> removes unwanted comment and clarifies

docs/004_release-notes/001_platform/8/8.10/auth.mdx, docs/004_release-notes/001_platform/8/8.10/documents.mdx, docs/004_release-notes/001_platform/8/8.10/fix.mdx, docs/004_release-notes/001_platform/8/8.10/integrations.mdx, docs/004_release-notes/001_platform/8/8.10/reconciliation.mdx, docs/004_release-notes/001_platform/8/8.10/reporting.mdx, docs/004_release-notes/001_platform/8/8.10/symphony.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx, release_note_formatter.py
=> Release tweaks

docs/001_develop/02_server-capabilities/016_testing-api/index.mdx
=> add docs around new genesis junit features

docs/001_develop/02_server-capabilities/003_data-access-apis/index.mdx
=> add docs around `generateCompactToString`

docs/004_release-notes/001_platform/8/8.10/index.mdx, docs/004_release-notes/001_platform/8/8.2/index.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx, docs/004_release-notes/001_platform/8/8.9/index.mdx, release_note_formatter.py
=> Release component tidyup

docs/004_release-notes/001_platform/8/8.0/index.mdx, docs/004_release-notes/001_platform/8/8.1/index.mdx, docs/004_release-notes/001_platform/8/8.10/index.mdx, docs/004_release-notes/001_platform/8/8.2/index.mdx, docs/004_release-notes/001_platform/8/8.3/index.mdx, docs/004_release-notes/001_platform/8/8.4/index.mdx, docs/004_release-notes/001_platform/8/8.5/index.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx, docs/004_release-notes/001_platform/8/8.7/index.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx, docs/004_release-notes/001_platform/8/8.9/index.mdx, release_note_formatter.py, release_note_unique_components.py
=> Adding release 8.8.13

docs/001_develop/03_client-capabilities/013_toast-notifications/index.mdx
=> ptl-1898: remove unsupported types from snackbar doc

docs/001_develop/02_server-capabilities/004_real-time-queries-data-server/index.mdx, docs/001_develop/02_server-capabilities/005_snapshot-queries-request-server/index.mdx, docs/001_develop/02_server-capabilities/006_core-business-logic-event-handler/index.mdx, docs/001_develop/02_server-capabilities/011_integrations/04_custom-endpoints/index.mdx, docs/001_develop/02_server-capabilities/016_testing-api/01_legacy-testing-api/_category_.yml, docs/001_develop/02_server-capabilities/016_testing-api/01_legacy-testing-api/index.mdx, docs/001_develop/02_server-capabilities/016_testing-api/index.mdx
=> feat: move legacy testing to subpage (PTL-1899)

docs/004_release-notes/001_platform/8/8.10/index.mdx, docs/004_release-notes/001_platform/8/8.2/index.mdx, docs/004_release-notes/001_platform/8/8.6/index.mdx
=> Adding latest patch release notes

docs/001_develop/02_server-capabilities/004_real-time-queries-data-server/index.mdx, docs/003_build-deploy-operate/03_operate/002_commands/02_dbmon.mdx
=> added information on LMDB warning state

docs/004_release-notes/001_platform/8/8.6/index.mdx, docs/004_release-notes/001_platform/8/8.8/auth.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx, release_note_formatter.py
=> Adding latest release's release notes

docs/001_develop/02_server-capabilities/005_snapshot-queries-request-server/index.mdx
=> PTL-1881: simplified pull request for adding a new example to reqrep

docs/001_develop/03_client-capabilities/007_forms/003_form-inputs/text-area.mdx
=> PTL-1912: correct code snippet in Text Area

docs/001_develop/03_client-capabilities/015_layout-management/index.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/002_fdc3-channel-event.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/003_channel-context-listener.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/004_system-channel-listener.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/005_listen_intent.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/006_interop_notifications_listener.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/007_openfin-notifications-listener.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/01_foundation-fdc3.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/01_foundation-openfin.mdx, docs/001_develop/03_client-capabilities/021_desktop-interoperability/index.mdx, docs/_includes/_fdc3-browsers.mdx
=> PTL-1798: FCD3 review

docs/003_build-deploy-operate/03_operate/002_commands/02_dbmon.mdx
=> PTL-1137: add missing descriptions to dbmon commands

.github/pull_request_template.md
=> PTL-1913: update readme and point to shorter contribs guide

docs/001_develop/02_server-capabilities/008_access-control/03_authorization/index.mdx
=> Re-add lost changes around chronicle map guidance on auth perms

docs/001_develop/02_server-capabilities/017_runtime-configuration/02_system-definition/index.mdx, docs/004_release-notes/001_platform/8/8.11/_category_.yml, docs/004_release-notes/001_platform/8/8.11/auth.mdx, docs/004_release-notes/001_platform/8/8.11/documents.mdx, docs/004_release-notes/001_platform/8/8.11/fix.mdx, docs/004_release-notes/001_platform/8/8.11/index.mdx, docs/004_release-notes/001_platform/8/8.11/integrations.mdx, docs/004_release-notes/001_platform/8/8.11/notify.mdx, docs/004_release-notes/001_platform/8/8.11/reconciliation.mdx, docs/004_release-notes/001_platform/8/8.11/reporting.mdx, docs/004_release-notes/001_platform/8/8.11/symphony.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx, docs/004_release-notes/index.mdx
=> Rel 8 11 release notes

docs/001_develop/02_server-capabilities/011_integrations/01_data-pipelines/index.mdx
=> feat(genesis-pal-datapipeline): add delayBetweenBatches + delayBetweenReads to db batch polling source (GSF-7296)

docs/001_develop/02_server-capabilities/009_real-time-aggregation-consolidator/index.mdx, docs/004_release-notes/001_platform/8/8.10/index.mdx, docs/004_release-notes/001_platform/8/8.8/auth.mdx, docs/004_release-notes/001_platform/8/8.8/index.mdx
=> Adding new releases and adding some backticks

docs/001_develop/02_server-capabilities/011_integrations/01_data-pipelines/index.mdx, docs/004_release-notes/001_platform/8/8.12/index.mdx
=> camel file source - single consumer (GSF-7341)

docs/001_develop/02_server-capabilities/011_integrations/01_data-pipelines/index.mdx, docs/004_release-notes/001_platform/8/8.12/_category_.yml, docs/004_release-notes/001_platform/8/8.12/auth.mdx, docs/004_release-notes/001_platform/8/8.12/documents.mdx, docs/004_release-notes/001_platform/8/8.12/fix.mdx, docs/004_release-notes/001_platform/8/8.12/index.mdx, docs/004_release-notes/001_platform/8/8.12/integrations.mdx, docs/004_release-notes/001_platform/8/8.12/notify.mdx, docs/004_release-notes/001_platform/8/8.12/reconciliation.mdx, docs/004_release-notes/001_platform/8/8.12/reporting.mdx, docs/004_release-notes/001_platform/8/8.12/symphony.mdx, docs/004_release-notes/index.mdx
=> Release 8 12

docs/001_develop/03_client-capabilities/024_testing/index.mdx, docs/001_develop/03_client-capabilities/025_env-files/_category_.yml, docs/001_develop/03_client-capabilities/025_env-files/index.mdx
=> feat: Adding env file docs (PTL-1954)

docs/001_develop/03_client-capabilities/007_forms/002_smart-forms/03_layouts.mdx, docs/001_develop/03_client-capabilities/007_forms/002_smart-forms/examples/array_layout_example.js
=> chore: Adding child ui schema to array form example (PTL-0)

docs/001_develop/03_client-capabilities/008_interaction/date-picker.mdx, examples/ui/client-capabilities/interaction/date-picker.js
https://genesisglobal.atlassian.net/browse/PTL-1937
__________
=> feat: Adding docs for date picker (PTL-1937)

docs/001_develop/03_client-capabilities/005_grids/003_grid-pro/grid-pro_02_datasources.mdx
=> feat: datasource events (PTL-1953)

docs/001_develop/03_client-capabilities/024_testing/index.mdx
=> Removing next step as it's not working

docs/001_develop/02_server-capabilities/018_model_context_protocol/_category_.yml, docs/001_develop/02_server-capabilities/018_model_context_protocol/index.mdx
=> feat: Added docs for new MCP server capability

docs/001_develop/02_server-capabilities/016_testing-api/index.mdx
=> docs: document "clear" method usage and fix wrong "revoke" code sample for Kotlin in the EnableInMemoryTestAuthCache docs (PTL-1944)

docs/001_develop/02_server-capabilities/017_runtime-configuration/02_system-definition/index.mdx
=> docs: add explanation for LOCAL_HOST behaviour and system definition resolution for system config blocks (PTL-1942)

docs/001_develop/02_server-capabilities/011_integrations/01_data-pipelines/index.mdx
=> feat: Make username and password optional for JMS source and sinks (PTL-1853)

docs/001_develop/03_client-capabilities/007_forms/003_form-inputs/multiselect.mdx
=> feat: multiselect added docs for itemRenderer, slots and attributes FUI-2324 

docs/003_build-deploy-operate/01_build/006_plugins/index.mdx
=> Add section on Exec plugin to explain configuring open telemetry locally

docs/001_develop/02_server-capabilities/011_integrations/05_external-rest-apis/index.mdx
=> docs: Add imports to external-rest-apis docs code snippets and fix wrong examples (PTL-1967) (PTL-1968)
